package com.loanzo.app.util

/**
 * High-performance, zero-latency on-device multi-language dictionary.
 * Contains pre-compiled offline translations for all core application terms across Indian languages.
 */
object AppGlossary {

    private val glossary_hi = mapOf<String, String>(
        "created on" to "बनाया गया दिनांक",
        "repaid on" to "चुकाया दिनांक",
        "disbursed on" to "संवितरित दिनांक",
        "in progress" to "प्रगति पर है",
        "step" to "कदम",
        "restructure loan" to "ऋण पुनर्गठन करें",
        "settlement" to "समझौता",
        "mediation" to "मध्यस्थता",
        "schedule mediation" to "मध्यस्थता निर्धारित करें",
        "anti-harassment sos" to "एंटी-उत्पीड़न एसओएस",
        "dispute tribunal" to "विवाद न्यायाधिकरण",
        "select option" to "विकल्प चुनें",
        "upi transaction reference" to "UPI लेनदेन संदर्भ संख्या",
        "quick select" to "त्वरित चयन",
        "i am a" to "मैं एक हूँ",
        "join the verified lending platform" to "सत्यापित ऋण मंच से जुड़ें",
        "verified loan utilization" to "सत्यापित ऋण उपयोगिता",
        "certified agent cockpit & doorstep visits" to "प्रमाणित एजेंट कॉकपिट और डोरस्टेप विज़िट",
        "verify identity (digilocker kyc)" to "पहचान सत्यापित करें (डिजिलॉकर केवाईसी)",
        "calculate loan emi & savings" to "ऋण EMI और बचत की गणना करें",
        "explore community loan wall" to "सामुदायिक ऋण मंच देखें",
        "submit tranche request" to "किस्त अनुरोध जमा करें",
        "rule engine result" to "नियम इंजन परिणाम",
        "weight (grams)" to "वजन (ग्राम)",
        "estimated value" to "अनुमानित मूल्य",
        "asset type" to "संपत्ति का प्रकार",
        "asset description" to "संपत्ति का विवरण",
        "asset collateral details" to "संपत्ति गिरवी विवरण",
        "payee upi id" to "प्राप्तकर्ता UPI आईडी",
        "payee name" to "प्राप्तकर्ता का नाम",
        "request tranche" to "किस्त (Tranche) का अनुरोध करें",
        "incorrect password" to "गलत पासवर्ड",
        "unlock" to "अनलॉक करें",
        "enter password to unlock" to "अनलॉक करने के लिए पासवर्ड दर्ज करें",
        "unlock document vault" to "दस्तावेज़ वॉल्ट अनलॉक करें",
        "close" to "बंद करें",
        "are you sure you want to sign out?" to "क्या आप वाकई साइन आउट करना चाहते हैं?",
        "confirm logout" to "लॉग आउट की पुष्टि करें",
        "home" to "होम",
        "loans" to "ऋण",
        "loan" to "ऋण",
        "alerts" to "अलर्ट",
        "profile" to "प्रोफ़ाइल",
        "notifications" to "सूचनाएं",
        "marketplace" to "बाज़ार",
        "explore marketplace" to "बाज़ार देखें",
        "community wall" to "सामुदायिक मंच",
        "community loan wall" to "सामुदायिक ऋण मंच",
        "portfolio overview" to "पोर्टफोलियो अवलोकन",
        "active portfolio value" to "सक्रिय पोर्टफोलियो मूल्य",
        "real-time capital balance" to "वास्तविक समय पूंजी शेष",
        "recent activity" to "हाल की गतिविधि",
        "quick actions" to "त्वरित क्रियाएं",
        "apply for loan" to "ऋण के लिए आवेदन करें",
        "create new loan" to "नया ऋण बनाएं",
        "manage all loans" to "सभी ऋण प्रबंधित करें",
        "my loans" to "मेरे ऋण",
        "active loans" to "सक्रिय ऋण",
        "total lent" to "कुल दिया गया ऋण",
        "total borrowed" to "कुल लिया गया ऋण",
        "lent out" to "दिया गया ऋण",
        "borrowed" to "लिया गया ऋण",
        "total outstanding" to "कुल बकाया",
        "total disbursed" to "कुल संवितरित",
        "total paid" to "कुल भुगतान",
        "sanctioned amount" to "स्वीकृत राशि",
        "outstanding balance" to "बकाया राशि",
        "monthly emi" to "मासिक ईएमआई",
        "interest rate" to "ब्याज दर",
        "tenure" to "अवधि",
        "tenure (months)" to "अवधि (महीने)",
        "loan amount" to "ऋण राशि",
        "purpose" to "उद्देश्य",
        "repay now" to "अभी चुकाएं",
        "make repayment" to "चुकौती करें",
        "repayment schedule" to "चुकौती अनुसूची",
        "repayment history" to "चुकौती इतिहास",
        "member" to "सदस्य",
        "user" to "उपयोगकर्ता",
        "borrower" to "उधारकर्ता",
        "lender" to "ऋणदाता",
        "field agent" to "फ़ील्ड एजेंट",
        "master admin" to "मास्टर एडमिन",
        "app owner" to "ऐप ओनर",
        "guarantor" to "गारंटर",
        "in-app role switcher" to "इन-ऐप भूमिका स्विचर",
        "verified" to "सत्यापित",
        "pending" to "लंबित",
        "approved" to "स्वीकृत",
        "rejected" to "अस्वीकृत",
        "completed" to "पूर्ण",
        "sanctioned" to "स्वीकृत",
        "disbursed" to "संवितरित",
        "repaid" to "चुकाया",
        "overdue" to "अतिदेय",
        "active" to "सक्रिय",
        "closed" to "समाप्त",
        "locked" to "लॉक 🔒",
        "unlocked" to "अनलॉक 🔓",
        "on duty" to "ड्यूटी पर",
        "off duty" to "ऑफ ड्यूटी",
        "settings" to "सेटिंग्स",
        "app language" to "ऐप भाषा",
        "change language" to "भाषा बदलें",
        "select app language" to "ऐप भाषा चुनें",
        "appearance" to "उपस्थिति",
        "sign out" to "साइन आउट",
        "logout" to "लॉग आउट",
        "trust score" to "विश्वास स्कोर",
        "digilocker" to "डिजिलॉकर",
        "vault" to "वॉल्ट",
        "kyc verification" to "केवाईसी सत्यापन",
        "bank details" to "बैंक विवरण",
        "bank accounts" to "बैंक खाते",
        "security & biometrics" to "सुरक्षा और बायोमेट्रिक्स",
        "help & support" to "सहायता और समर्थन",
        "loan calculator" to "ऋण कैलकुलेटर",
        "save" to "सहेजें",
        "cancel" to "रद्द करें",
        "clear" to "साफ़ करें",
        "submit" to "जमा करें",
        "confirm" to "पुष्टि करें",
        "continue" to "जारी रखें",
        "next" to "आगे बढ़ें",
        "back" to "पीछे",
        "search" to "खोजें",
        "edit" to "संपादित करें",
        "delete" to "हटाएं",
        "upload" to "अपलोड करें",
        "download" to "डाउनलोड करें",
        "sign in" to "साइन इन करें",
        "create account" to "खाता बनाएं",
        "register" to "पंजीकरण करें",
        "phone number" to "फ़ोन नंबर",
        "email address" to "ईमेल पता",
        "full name" to "पूरा नाम",
        "password" to "पासवर्ड",
        "welcome to loanzo" to "लोनज़ो में आपका स्वागत है",
        "welcome back" to "वापसी पर स्वागत है",
        "thank you" to "धन्यवाद",
        "yes" to "हाँ",
        "no" to "नहीं",
        "ok" to "ठीक है",
        "okay" to "ठीक है",
        "all offers" to "सभी ऑफ़र",
        "lenders" to "ऋणदाता",
        "borrowers" to "उधारकर्ता",
        "my posts" to "मेरी पोस्ट",
        "post" to "पोस्ट",
        "create post" to "पोस्ट बनाएं",
        "bid" to "बोली लगाएं",
        "bids" to "बोलियां",
        "submit bid" to "बोली जमा करें",
        "vouch" to "सत्यापन / गवाही",
        "vouches" to "गवाहियां",
        "vouch for post" to "इस पोस्ट के लिए गवाही दें",
        "all" to "सभी",
        "filter" to "फ़िल्टर",
        "sort" to "क्रमबद्ध करें",
        "chat" to "चैट",
        "report" to "रिपोर्ट",
        "simulator" to "सिम्युलेटर",
        "guide" to "गाइड",
        "interactive guide" to "इंटरैक्टिव गाइड",
        "loan details" to "ऋण विवरण",
        "principal" to "मूलधन",
        "interest" to "ब्याज",
        "penalty" to "दंड / पेनल्टी",
        "due date" to "देय तिथि",
        "status" to "स्थिति",
        "amount" to "राशि",
        "date" to "दिनांक",
        "time" to "समय",
        "upi id" to "यूपीआई आईडी",
        "account number" to "खाता संख्या",
        "ifsc code" to "आईएफएससी कोड",
        "bank name" to "बैंक का नाम",
        "pan number" to "पैन नंबर",
        "aadhaar number" to "आधार नंबर",
        "doorstep visits" to "डोरस्टेप विज़िट",
        "field agent cockpit" to "फ़ील्ड एजेंट कॉकपिट",
        "platform overview" to "प्लेटफ़ॉर्म अवलोकन",
        "audit trail" to "ऑडिट ट्रेल",
        "add pledge" to "गिरवी जोड़ें",
        "disbursement request" to "संवितरण अनुरोध",
        "sign agreement" to "समझौते पर हस्ताक्षर करें",
        "pay now" to "अभी भुगतान करें",
        "pay directly with upi app" to "सीधे UPI ऐप से भुगतान करें",
        "sign in to your account" to "अपने खाते में साइन इन करें",
        "fast-track with didit ai" to "डिडिट एआई के साथ फास्ट-ट्रैक",
        "30 sec kyc" to "30 सेकंड केवाईसी",
        "or manual verification" to "या मैन्युअल सत्यापन",
        "complete kyc" to "केवाईसी पूरा करें",
        "kyc complete!" to "केवाईसी पूर्ण!",
        "your profile is now verified" to "अब आपकी प्रोफ़ाइल सत्यापित हो गई है",
        "borrower dashboard" to "उधारकर्ता डैशबोर्ड",
        "lender dashboard" to "ऋणदाता डैशबोर्ड",
        "tab_lent" to "दिया गया (Lent)",
        "tab_borrowed" to "लिया गया (Borrowed)",
        "total" to "कुल",
        "enter upi transaction id" to "UPI लेनदेन आईडी दर्ज करें",
        "save signature" to "हस्ताक्षर सहेजें",
        "loan dashboard" to "ऋण डैशबोर्ड"
    )

    private val glossary_mr = mapOf<String, String>(
        "created on" to "तयार केल्याची तारीख",
        "repaid on" to "परतफेड तारीख",
        "disbursed on" to "वितरित तारीख",
        "in progress" to "प्रगतीपथावर आहे",
        "step" to "पायरी",
        "restructure loan" to "कर्ज पुनर्रचना करा",
        "settlement" to "तडजोड",
        "mediation" to "मध्यस्थता",
        "schedule mediation" to "मध्यस्थता शेड्यूल करा",
        "anti-harassment sos" to "अँटी-छळ एसओएस",
        "dispute tribunal" to "वाद न्यायाधिकरण",
        "select option" to "पर्याय निवडा",
        "upi transaction reference" to "UPI व्यवहार संदर्भ",
        "quick select" to "जलद निवड",
        "i am a" to "मी एक आहे",
        "join the verified lending platform" to "सत्यापित कर्ज मंचाशी जोडा",
        "verified loan utilization" to "सत्यापित कर्ज उपयोगिता",
        "certified agent cockpit & doorstep visits" to "प्रमाणित एजंट कॉकपिट आणि घरोघरी भेट",
        "verify identity (digilocker kyc)" to "ओळख सत्यापित करा (डिजीलॉकर KYC)",
        "calculate loan emi & savings" to "कर्ज EMI आणि बचतीची गणना करा",
        "explore community loan wall" to "सामुदायिक कर्ज मंच पहा",
        "submit tranche request" to "हप्ता विनंती सबमिट करा",
        "rule engine result" to "नियम इंजिन निकाल",
        "weight (grams)" to "वजन (ग्रॅम)",
        "estimated value" to "अंदाजे मूल्य",
        "asset type" to "मालमत्तेचा प्रकार",
        "asset description" to "मालमत्तेचे वर्णन",
        "asset collateral details" to "तारण मालमत्ता तपशील",
        "payee upi id" to "मिळणाऱ्याचा UPI आयडी",
        "payee name" to "पैसे मिळणाऱ्याचे नाव",
        "request tranche" to "हप्त्याची विनंती करा",
        "incorrect password" to "चुकीचा पासवर्ड",
        "unlock" to "अनलॉक करा",
        "enter password to unlock" to "अनलॉक करण्यासाठी पासवर्ड टाका",
        "unlock document vault" to "दस्तऐवज वॉल्ट अनलॉक करा",
        "close" to "बंद करा",
        "are you sure you want to sign out?" to "तुम्हाला नक्की साइन आउट करायचे आहे का?",
        "confirm logout" to "लॉग आउटची पुष्टी करा",
        "home" to "होम",
        "loans" to "कर्ज",
        "loan" to "कर्ज",
        "alerts" to "सूचना",
        "profile" to "प्रोफाइल",
        "notifications" to "सूचना",
        "marketplace" to "बाजार",
        "explore marketplace" to "बाजार एक्सप्लोर करा",
        "community wall" to "सामुदायिक मंच",
        "community loan wall" to "सामुदायिक कर्ज मंच",
        "portfolio overview" to "पोर्टफोलिओ आढावा",
        "active portfolio value" to "सक्रिय पोर्टफोलिओ मूल्य",
        "real-time capital balance" to "रिअल-टाइम भांडवल शिल्लक",
        "recent activity" to "अलीकडील क्रियाकलाप",
        "quick actions" to "जलद कृती",
        "apply for loan" to "कर्जासाठी अर्ज करा",
        "create new loan" to "नवीन कर्ज तयार करा",
        "manage all loans" to "सर्व कर्ज व्यवस्थापित करा",
        "my loans" to "माझे कर्ज",
        "active loans" to "सक्रिय कर्ज",
        "total lent" to "एकूण दिलेले कर्ज",
        "total borrowed" to "एकूण घेतलेले कर्ज",
        "lent out" to "दिलेले कर्ज",
        "borrowed" to "घेतलेले कर्ज",
        "total outstanding" to "एकूण थकबाकी",
        "total disbursed" to "एकूण वितरित",
        "total paid" to "एकूण भरलेले",
        "sanctioned amount" to "मंजूर रक्कम",
        "outstanding balance" to "थकबाकी शिल्लक",
        "monthly emi" to "मासिक ईएमआय",
        "interest rate" to "व्याज दर",
        "tenure" to "कालावधी",
        "tenure (months)" to "कालावधी (महिने)",
        "loan amount" to "कर्ज रक्कम",
        "purpose" to "हेतू",
        "repay now" to "आत्ता परतफेड करा",
        "make repayment" to "परतफेड करा",
        "repayment schedule" to "परतफेड वेळापत्रक",
        "repayment history" to "परतफेड इतिहास",
        "member" to "सदस्य",
        "user" to "वापरकर्ता",
        "borrower" to "कर्जदार",
        "lender" to "कर्जदाता",
        "field agent" to "फील्ड एजंट",
        "master admin" to "मास्टर ॲडमिन",
        "app owner" to "ॲप मालक",
        "guarantor" to "हमीदार",
        "in-app role switcher" to "इन-ॲप भूमिका स्विचर",
        "verified" to "सत्यापित",
        "pending" to "प्रलंबित",
        "approved" to "मंजूर",
        "rejected" to "नाकारले",
        "completed" to "पूर्ण",
        "sanctioned" to "मंजूर",
        "disbursed" to "वितरित",
        "repaid" to "परतफेड केली",
        "overdue" to "मुदत संपलेली",
        "active" to "सक्रिय",
        "closed" to "बंद",
        "locked" to "लॉक 🔒",
        "unlocked" to "अनलॉक 🔓",
        "on duty" to "कामावर",
        "off duty" to "रजेवर",
        "settings" to "सेटिंग्ज",
        "app language" to "ॲप भाषा",
        "change language" to "भाषा बदला",
        "select app language" to "ॲप भाषा निवडा",
        "appearance" to "दिसणे",
        "sign out" to "साइन आउट",
        "logout" to "लॉग आउट",
        "trust score" to "विश्वास स्कोअर",
        "digilocker" to "डिजीलॉकर",
        "vault" to "वॉल्ट",
        "kyc verification" to "केवायसी पडताळणी",
        "bank details" to "बँक तपशील",
        "bank accounts" to "बँक खाती",
        "security & biometrics" to "सुरक्षा आणि बायोमेट्रिक्स",
        "help & support" to "मदत आणि समर्थन",
        "loan calculator" to "कर्ज कॅल्क्युलेटर",
        "save" to "जतन करा",
        "cancel" to "रद्द करा",
        "clear" to "साफ करा",
        "submit" to "सबमिट करा",
        "confirm" to "पुष्टी करा",
        "continue" to "पुढे सुरू ठेवा",
        "next" to "पुढे",
        "back" to "मागे",
        "search" to "शोधा",
        "edit" to "संपादित करा",
        "delete" to "हटवा",
        "upload" to "अपलोड करा",
        "download" to "डाउनलोड करा",
        "sign in" to "साइन इन करा",
        "create account" to "खाते तयार करा",
        "register" to "नोंदणी करा",
        "phone number" to "फोन नंबर",
        "email address" to "ईमेल पत्ता",
        "full name" to "पूर्ण नाव",
        "password" to "पासवर्ड",
        "welcome to loanzo" to "लोनझो मध्ये आपले स्वागत आहे",
        "welcome back" to "पुन्हा स्वागत आहे",
        "thank you" to "धन्यवाद",
        "yes" to "होय",
        "no" to "नाही",
        "ok" to "ठीक आहे",
        "okay" to "ठीक आहे",
        "all offers" to "सर्व ऑफर",
        "lenders" to "कर्जदाते",
        "borrowers" to "कर्जदार",
        "my posts" to "माझ्या पोस्ट",
        "post" to "पोस्ट",
        "create post" to "पोस्ट तयार करा",
        "bid" to "बोली लावा",
        "bids" to "बोली",
        "submit bid" to "बोली सबमिट करा",
        "vouch" to "हमी द्या",
        "vouches" to "हमी",
        "vouch for post" to "या पोस्टसाठी हमी द्या",
        "all" to "सर्व",
        "filter" to "फिल्टर",
        "sort" to "क्रमवारी लावा",
        "chat" to "चॅट",
        "report" to "अहवाल",
        "simulator" to "सिम्युलेटर",
        "guide" to "मार्गदर्शक",
        "interactive guide" to "परस्परसंवादी मार्गदर्शक",
        "loan details" to "कर्ज तपशील",
        "principal" to "मुद्दल",
        "interest" to "व्याज",
        "penalty" to "दंड",
        "due date" to "देय तारीख",
        "status" to "स्थिती",
        "amount" to "रक्कम",
        "date" to "तारीख",
        "time" to "वेळ",
        "upi id" to "यूपीआय आयडी",
        "account number" to "खाते क्रमांक",
        "ifsc code" to "आयएफएससी कोड",
        "bank name" to "बँकेचे नाव",
        "pan number" to "पॅन क्रमांक",
        "aadhaar number" to "आधार क्रमांक",
        "doorstep visits" to "घरोघरी भेट",
        "field agent cockpit" to "फील्ड एजंट कॉकपिट",
        "platform overview" to "प्लॅटफॉर्म आढावा",
        "audit trail" to "ऑडिट ट्रेल",
        "add pledge" to "तारण जोडा",
        "disbursement request" to "वितरण विनंती",
        "sign agreement" to "करारावर स्वाक्षरी करा",
        "pay now" to "आत्ता भरा",
        "pay directly with upi app" to "थेट UPI ॲपने पैसे भरा",
        "sign in to your account" to "आपल्या खात्यात साइन इन करा",
        "fast-track with didit ai" to "डिडिट एआय सह फास्ट-ट्रॅक",
        "30 sec kyc" to "30 सेकंद केवायसी",
        "or manual verification" to "किंवा मॅन्युअल पडताळणी",
        "complete kyc" to "केवायसी पूर्ण करा",
        "kyc complete!" to "केवायसी पूर्ण!",
        "your profile is now verified" to "तुमची प्रोफाइल आता सत्यापित झाली आहे",
        "borrower dashboard" to "कर्जदार डॅशबोर्ड",
        "lender dashboard" to "कर्जदाता डॅशबोर्ड",
        "tab_lent" to "दिलेले (Lent)",
        "tab_borrowed" to "घेतलेले (Borrowed)",
        "total" to "एकूण",
        "enter upi transaction id" to "UPI व्यवहार आयडी प्रविष्ट करा",
        "save signature" to "स्वाक्षरी जतन करा",
        "loan dashboard" to "कर्ज डॅशबोर्ड"
    )

    private val glossary_gu = mapOf<String, String>(
        "created on" to "બનાવ્યા તારીખ",
        "repaid on" to "ચુકવણી તારીખ",
        "disbursed on" to "વિતરણ તારીખ",
        "in progress" to "પ્રગતિમાં છે",
        "step" to "પગલું",
        "restructure loan" to "લોન પુનર્ગઠન કરો",
        "settlement" to "સમજૂતી",
        "mediation" to "મધ્યસ્થી",
        "schedule mediation" to "મધ્યસ્થી શેડ્યૂલ કરો",
        "anti-harassment sos" to "એન્ટી-હેરાસમેન્ટ SOS",
        "dispute tribunal" to "વિવાદ ટ્રિબ્યુનલ",
        "select option" to "વિકલ્પ પસંદ કરો",
        "upi transaction reference" to "UPI ટ્રાન્ઝેક્શન સંદર્ભ",
        "quick select" to "ઝડપી પસંદગી",
        "i am a" to "હું એક છું",
        "join the verified lending platform" to "ચકાસાયેલ ધિરાણ પ્લેટફોર્મ સાથે જોડાઓ",
        "verified loan utilization" to "ચકાસાયેલ લોન ઉપયોગિતા",
        "certified agent cockpit & doorstep visits" to "પ્રમાણિત એજન્ટ કોકપિટ અને ડોરસ્ટેપ મુલાકાતો",
        "verify identity (digilocker kyc)" to "ઓળખ ચકાસો (ડિજિલોકર KYC)",
        "calculate loan emi & savings" to "લોન EMI અને બચતની ગણતરી કરો",
        "explore community loan wall" to "કમ્યુનિટી લોન વૉલ જુઓ",
        "submit tranche request" to "હપ્તા વિનંતી સબમિટ કરો",
        "rule engine result" to "રૂલ એન્જિન પરિણામ",
        "weight (grams)" to "વજન (ગ્રામ)",
        "estimated value" to "અંદાજિત મૂલ્ય",
        "asset type" to "સંપત્તિનો પ્રકાર",
        "asset description" to "સંપત્તિનું વર્ણન",
        "asset collateral details" to "સંપત્તિ ગીરો વિગતો",
        "payee upi id" to "ચૂકવણી મેળવનારનો UPI આઈડી",
        "payee name" to "ચૂકવણી મેળવનારનું નામ",
        "request tranche" to "હપ્તાની વિનંતી કરો",
        "incorrect password" to "ખોટો પાસવર્ડ",
        "unlock" to "અનલૉક કરો",
        "enter password to unlock" to "અનલૉક કરવા માટે પાસવર્ડ દાખલ કરો",
        "unlock document vault" to "દસ્તાવેજ વોલ્ટ અનલૉક કરો",
        "close" to "બંધ કરો",
        "are you sure you want to sign out?" to "શું તમે ખરેખર સાઇન આઉટ કરવા માંગો છો?",
        "confirm logout" to "લૉગ આઉટની પુષ્ટિ કરો",
        "home" to "હોમ",
        "loans" to "લોન",
        "loan" to "લોન",
        "alerts" to "ચેતવણીઓ",
        "profile" to "પ્રોફાઇલ",
        "notifications" to "સૂચનાઓ",
        "marketplace" to "માર્કેટપ્લેસ",
        "explore marketplace" to "માર્કેટપ્લેસ જુઓ",
        "community wall" to "કમ્યુનિટી વૉલ",
        "community loan wall" to "કમ્યુનિટી લોન વૉલ",
        "portfolio overview" to "પોર્ટફોલિયો ઝાંખી",
        "active portfolio value" to "સક્રિય પોર્ટફોલિયો મૂલ્ય",
        "real-time capital balance" to "રીઅલ-ટાઇમ મૂડી બેલેન્સ",
        "recent activity" to "તાજેતરની પ્રવૃત્તિ",
        "quick actions" to "ઝડપી ક્રિયાઓ",
        "apply for loan" to "લોન માટે અરજી કરો",
        "create new loan" to "નવી લોન બનાવો",
        "manage all loans" to "બધી લોન મેનેજ કરો",
        "my loans" to "મારી લોન",
        "active loans" to "સક્રિય લોન",
        "total lent" to "કુલ ધિરાણ",
        "total borrowed" to "કુલ લીધેલી લોન",
        "lent out" to "ધીરેલું",
        "borrowed" to "ઉધાર લીધેલું",
        "total outstanding" to "કુલ બાકી",
        "total disbursed" to "કુલ વિતરિત",
        "total paid" to "કુલ ચૂકવેલ",
        "sanctioned amount" to "મંજૂર રકમ",
        "outstanding balance" to "બાકી રકમ",
        "monthly emi" to "માસિક EMI",
        "interest rate" to "વ્યાજ દર",
        "tenure" to "મુદ્દત",
        "tenure (months)" to "મુદ્દત (મહિના)",
        "loan amount" to "લોન રકમ",
        "purpose" to "હેતુ",
        "repay now" to "હમણાં ચૂકવો",
        "make repayment" to "ચુકવણી કરો",
        "repayment schedule" to "ચુકવણી સમયપત્રક",
        "repayment history" to "ચુકવણી ઇતિહાસ",
        "member" to "સભ્ય",
        "user" to "વપરાશકર્તા",
        "borrower" to "ઉધાર લેનાર",
        "lender" to "ધિરાણકર્તા",
        "field agent" to "ફીલ્ડ એજન્ટ",
        "master admin" to "માસ્ટર એડમિન",
        "app owner" to "ઍપ માલિક",
        "guarantor" to "જામીનદાર",
        "in-app role switcher" to "ઇન-એપ રોલ સ્વિચર",
        "verified" to "ચકાસાયેલ",
        "pending" to "બાકી",
        "approved" to "મંજૂર",
        "rejected" to "અસ્વીકાર્ય",
        "completed" to "પૂર્ણ",
        "sanctioned" to "મંજૂર",
        "disbursed" to "વિતરિત",
        "repaid" to "ચૂકવેલ",
        "overdue" to "મુદતવીતી",
        "active" to "સક્રિય",
        "closed" to "બંધ",
        "locked" to "લૉક 🔒",
        "unlocked" to "અનલૉક 🔓",
        "on duty" to "ઓન ડ્યુટી",
        "off duty" to "ઓફ ડ્યુટી",
        "settings" to "સેટિંગ્સ",
        "app language" to "ઍપ ભાષા",
        "change language" to "ભાષા બદલો",
        "select app language" to "ઍપ ભાષા પસંદ કરો",
        "appearance" to "દેખાવ",
        "sign out" to "સાઇન આઉટ",
        "logout" to "લૉગ આઉટ",
        "trust score" to "વિશ્વાસ સ્કોર",
        "digilocker" to "ડિજિલોકર",
        "vault" to "વોલ્ટ",
        "kyc verification" to "KYC ચકાસણી",
        "bank details" to "બેંક વિગતો",
        "bank accounts" to "બેંક ખાતાઓ",
        "security & biometrics" to "સુરક્ષા અને બાયોમેટ્રિક્સ",
        "help & support" to "મદદ અને આધાર",
        "loan calculator" to "લોન કેલ્ક્યુલેટર",
        "save" to "સાચવો",
        "cancel" to "રદ કરો",
        "clear" to "સાફ કરો",
        "submit" to "સબમિટ કરો",
        "confirm" to "પુષ્ટિ કરો",
        "continue" to "ચાલુ રાખો",
        "next" to "આગળ",
        "back" to "પાછળ",
        "search" to "શોધો",
        "edit" to "સંપાદિત કરો",
        "delete" to "કાઢી નાખો",
        "upload" to "અપલોડ કરો",
        "download" to "ડાઉનલોડ કરો",
        "sign in" to "સાઇન ઇન કરો",
        "create account" to "ખાતું બનાવો",
        "register" to "નોંધણી કરો",
        "phone number" to "ફોન નંબર",
        "email address" to "ઇમેઇલ સરનામું",
        "full name" to "પૂરું નામ",
        "password" to "પાસવર્ડ",
        "welcome to loanzo" to "લોનઝોમાં આપનું સ્વાગત છે",
        "welcome back" to "પાછા સ્વાગત છે",
        "thank you" to "આભાર",
        "yes" to "હા",
        "no" to "ના",
        "ok" to "બરાબર",
        "okay" to "બરાબર",
        "all offers" to "બધી ઑફર્સ",
        "lenders" to "ધિરાણકર્તાઓ",
        "borrowers" to "ઉધાર લેનારાઓ",
        "my posts" to "મારી પોસ્ટ્સ",
        "post" to "પોસ્ટ",
        "create post" to "પોસ્ટ બનાવો",
        "bid" to "બોલી લગાવો",
        "bids" to "બોલીઓ",
        "submit bid" to "બોલી સબમિટ કરો",
        "vouch" to "સમર્થન આપો",
        "vouches" to "સમર્થનો",
        "vouch for post" to "આ પોસ્ટ માટે સમર્થન આપો",
        "all" to "બધા",
        "filter" to "ફિલ્ટર",
        "sort" to "ક્રમબદ્ધ કરો",
        "chat" to "ચેટ",
        "report" to "અહેવાલ",
        "simulator" to "સિમ્યુલેટર",
        "guide" to "માર્ગદર્શિકા",
        "interactive guide" to "ઇન્ટરેક્ટિવ ગાઇડ",
        "loan details" to "લોન વિગતો",
        "principal" to "મુદ્દલ",
        "interest" to "વ્યાજ",
        "penalty" to "દંડ",
        "due date" to "ચુકવણી તારીખ",
        "status" to "સ્થિતિ",
        "amount" to "રકમ",
        "date" to "તારીખ",
        "time" to "સમય",
        "upi id" to "UPI આઈડી",
        "account number" to "ખાતા નંબર",
        "ifsc code" to "IFSC કોડ",
        "bank name" to "બેંકનું નામ",
        "pan number" to "પાન નંબર",
        "aadhaar number" to "આધાર નંબર",
        "doorstep visits" to "ડોરસ્ટેપ મુલાકાત",
        "field agent cockpit" to "ફીલ્ડ એજન્ટ કોકપિટ",
        "platform overview" to "પ્લેટફોર્મ ઝાંખી",
        "audit trail" to "ઓડિટ ટ્રેઇલ",
        "add pledge" to "ગીરો ઉમેરો",
        "disbursement request" to "વિતરણ વિનંતી",
        "sign agreement" to "કરાર પર સહી કરો",
        "pay now" to "હમણાં ચૂકવો",
        "pay directly with upi app" to "સીધા UPI ઍપ દ્વારા ચૂકવો",
        "sign in to your account" to "તમારા ખાતામાં સાઇન ઇન કરો",
        "fast-track with didit ai" to "ડીડિટ AI સાથે ફાસ્ટ-ટ્રેક",
        "30 sec kyc" to "30 સેકન્ડ KYC",
        "or manual verification" to "અથવા મેન્યુઅલ ચકાસણી",
        "complete kyc" to "KYC પૂર્ણ કરો",
        "kyc complete!" to "KYC પૂર્ણ!",
        "your profile is now verified" to "તમારી પ્રોફાઇલ હવે ચકાસાયેલ છે",
        "borrower dashboard" to "ઉધાર લેનાર ડેશબોર્ડ",
        "lender dashboard" to "ધિરાણકર્તા ડેશબોર્ડ",
        "tab_lent" to "ધીરેલું (Lent)",
        "tab_borrowed" to "લીધેલું (Borrowed)",
        "total" to "કુલ",
        "enter upi transaction id" to "UPI ટ્રાન્ઝેક્શન આઈડી દાખલ કરો",
        "save signature" to "સહી સાચવો",
        "loan dashboard" to "લોન ડેશબોર્ડ"
    )

    private val glossary_bn = mapOf<String, String>(
        "created on" to "তৈরির তারিখ",
        "repaid on" to "পরিশোধের তারিখ",
        "disbursed on" to "বিতরণের তারিখ",
        "in progress" to "চলমান",
        "step" to "ধাপ",
        "restructure loan" to "ঋণ পুনর্গঠন করুন",
        "settlement" to "নিষ্পত্তি",
        "mediation" to "সালিশ",
        "schedule mediation" to "সালিশ নির্ধারণ করুন",
        "anti-harassment sos" to "হয়রানি বিরোধী এসওএস",
        "dispute tribunal" to "বিরোধ ট্রাইব্যুনাল",
        "select option" to "বিকল্প নির্বাচন করুন",
        "upi transaction reference" to "ইউপিআই লেনদেন রেফারেন্স",
        "quick select" to "দ্রুত নির্বাচন",
        "i am a" to "আমি একজন",
        "join the verified lending platform" to "যাচাইকৃত ঋণ প্ল্যাটফর্মে যোগ দিন",
        "verified loan utilization" to "যাচাইকৃত ঋণ ব্যবহার",
        "certified agent cockpit & doorstep visits" to "প্রত্যয়িত এজেন্ট ককপিট ও ডোরস্টেপ পরিদর্শন",
        "verify identity (digilocker kyc)" to "পরিচয় যাচাই করুন (ডিজিলকার কেওয়াইসি)",
        "calculate loan emi & savings" to "ঋণ ইএমআই এবং সঞ্চয় গণনা করুন",
        "explore community loan wall" to "কমিউনিটি লোন ওয়াল অন্বেষণ করুন",
        "submit tranche request" to "কিস্তির অনুরোধ জমা দিন",
        "rule engine result" to "রুল ইঞ্জিন ফলাফল",
        "weight (grams)" to "ওজন (গ্রাম)",
        "estimated value" to "আনুমানিক মূল্য",
        "asset type" to "সম্পত্তির ধরন",
        "asset description" to "সম্পত্তির বিবরণ",
        "asset collateral details" to "সম্পত্তি বন্ধক বিবরণ",
        "payee upi id" to "প্রাপকের ইউপিআই আইডি",
        "payee name" to "প্রাপকের নাম",
        "request tranche" to "কিস্তির জন্য অনুরোধ করুন",
        "incorrect password" to "ভুল পাসওয়ার্ড",
        "unlock" to "আনলক করুন",
        "enter password to unlock" to "আনলক করতে পাসওয়ার্ড লিখুন",
        "unlock document vault" to "ডকুমেন্ট ভল্ট আনলক করুন",
        "close" to "বন্ধ করুন",
        "are you sure you want to sign out?" to "আপনি কি নিশ্চিত যে সাইন আউট করতে চান?",
        "confirm logout" to "লগ আউট নিশ্চিত করুন",
        "home" to "হোম",
        "loans" to "ঋণ",
        "loan" to "ঋণ",
        "alerts" to "সতর্কতা",
        "profile" to "প্রোফাইল",
        "notifications" to "বিজ্ঞপ্তি",
        "marketplace" to "মার্কেটপ্লেস",
        "explore marketplace" to "মার্কেটপ্লেস অন্বেষণ করুন",
        "community wall" to "কমিউনিটি ওয়াল",
        "community loan wall" to "কমিউনিটি লোন ওয়াল",
        "portfolio overview" to "পোর্টফোলিও ওভারভিউ",
        "active portfolio value" to "সক্রিয় পোর্টফোলিও মূল্য",
        "real-time capital balance" to "রিয়েল-টাইম মূলধন ব্যালেন্স",
        "recent activity" to "সাম্প্রতিক কার্যকলাপ",
        "quick actions" to "দ্রুত পদক্ষেপ",
        "apply for loan" to "ঋণের জন্য আবেদন করুন",
        "create new loan" to "নতুন ঋণ তৈরি করুন",
        "manage all loans" to "সমস্ত ঋণ পরিচালনা করুন",
        "my loans" to "আমার ঋণ",
        "active loans" to "সক্রিয় ঋণ",
        "total lent" to "মোট ধার দেওয়া",
        "total borrowed" to "মোট ধার নেওয়া",
        "lent out" to "ধার দেওয়া",
        "borrowed" to "ধার নেওয়া",
        "total outstanding" to "মোট বকেয়া",
        "total disbursed" to "মোট বিতরণ করা",
        "total paid" to "মোট পরিশোধ",
        "sanctioned amount" to "অনুমোদিত পরিমাণ",
        "outstanding balance" to "বকেয়া ব্যালেন্স",
        "monthly emi" to "মাসিক ইএমআই",
        "interest rate" to "সুদের হার",
        "tenure" to "মেয়াদ",
        "tenure (months)" to "মেয়াদ (মাস)",
        "loan amount" to "ঋণের পরিমাণ",
        "purpose" to "উদ্দেশ্য",
        "repay now" to "এখন পরিশোধ করুন",
        "make repayment" to "পরিশোধ করুন",
        "repayment schedule" to "পরিশোধের সময়সূচী",
        "repayment history" to "পরিশোধের ইতিহাস",
        "member" to "সদস্য",
        "user" to "ব্যবহারকারী",
        "borrower" to "ঋণগ্রহীতা",
        "lender" to "ঋণদাতা",
        "field agent" to "ফিল্ড এজেন্ট",
        "master admin" to "মাস্টার অ্যাডমিন",
        "app owner" to "অ্যাপের মালিক",
        "guarantor" to "জামিনদার",
        "in-app role switcher" to "ইন-অ্যাপ ভূমিকা পরিবর্তনকারী",
        "verified" to "যাচাইকৃত",
        "pending" to "বিচারাধীন",
        "approved" to "অনুমোদিত",
        "rejected" to "প্রত্যাখ্যাত",
        "completed" to "সম্পূর্ণ",
        "sanctioned" to "অনুমোদিত",
        "disbursed" to "বিতরণ করা",
        "repaid" to "পরিশোধিত",
        "overdue" to "বকেয়া মেয়াদোত্তীর্ণ",
        "active" to "সক্রিয়",
        "closed" to "বন্ধ",
        "locked" to "লক 🔒",
        "unlocked" to "আনলক 🔓",
        "on duty" to "কাজে নিযুক্ত",
        "off duty" to "ছুটিতে",
        "settings" to "সেটিংস",
        "app language" to "অ্যাপের ভাষা",
        "change language" to "ভাষা পরিবর্তন করুন",
        "select app language" to "অ্যাপের ভাষা নির্বাচন করুন",
        "appearance" to "উপস্থিতি",
        "sign out" to "সাইন আউট",
        "logout" to "লগ আউট",
        "trust score" to "বিশ্বাস স্কোর",
        "digilocker" to "ডিজিলকার",
        "vault" to "ভল্ট",
        "kyc verification" to "কেওয়াইসি যাচাইকরণ",
        "bank details" to "ব্যাংক বিবরণ",
        "bank accounts" to "ব্যাংক অ্যাকাউন্ট",
        "security & biometrics" to "নিরাপত্তা ও বায়োমেট্রিক্স",
        "help & support" to "সাহায্য ও সমর্থন",
        "loan calculator" to "ঋণ ক্যালকুলেটর",
        "save" to "সংরক্ষণ করুন",
        "cancel" to "বাতিল করুন",
        "clear" to "সাফ করুন",
        "submit" to "জমা দিন",
        "confirm" to "নিশ্চিত করুন",
        "continue" to "চালিয়ে যান",
        "next" to "পরবর্তী",
        "back" to "পেছনে",
        "search" to "অনুসন্ধান",
        "edit" to "সম্পাদনা করুন",
        "delete" to "মুছে ফেলুন",
        "upload" to "আপলোড করুন",
        "download" to "ডাউনলোড করুন",
        "sign in" to "সাইন ইন করুন",
        "create account" to "অ্যাকাউন্ট তৈরি করুন",
        "register" to "নিবন্ধন করুন",
        "phone number" to "ফোন নম্বর",
        "email address" to "ইমেল ঠিকানা",
        "full name" to "পুরো নাম",
        "password" to "পাসওয়ার্ড",
        "welcome to loanzo" to "লোনজোতে স্বাগতম",
        "welcome back" to "ফিরে আসার জন্য স্বাগতম",
        "thank you" to "ধন্যবাদ",
        "yes" to "হ্যাঁ",
        "no" to "না",
        "ok" to "ঠিক আছে",
        "okay" to "ঠিক আছে",
        "all offers" to "সমস্ত অফার",
        "lenders" to "ঋণদাতারা",
        "borrowers" to "ঋণগ্রহীতারা",
        "my posts" to "আমার পোস্ট",
        "post" to "পোস্ট",
        "create post" to "পোস্ট তৈরি করুন",
        "bid" to "বিড করুন",
        "bids" to "বিডসমূহ",
        "submit bid" to "বিড জমা দিন",
        "vouch" to "সাক্ষ্য দিন",
        "vouches" to "সাক্ষ্যসমূহ",
        "vouch for post" to "এই পোস্টের জন্য সাক্ষ্য দিন",
        "all" to "সব",
        "filter" to "ফিল্টার",
        "sort" to "সাজান",
        "chat" to "চ্যাট",
        "report" to "রিপোর্ট",
        "simulator" to "সিমুলেটর",
        "guide" to "নির্দেশিকা",
        "interactive guide" to "ইন্টারেক্টিভ গাইড",
        "loan details" to "ঋণের বিবরণ",
        "principal" to "আসল",
        "interest" to "সুদ",
        "penalty" to "জরিমানা",
        "due date" to "বকেয়া তারিখ",
        "status" to "অবস্থা",
        "amount" to "পরিমাণ",
        "date" to "তারিখ",
        "time" to "সময়",
        "upi id" to "ইউপিআই আইডি",
        "account number" to "অ্যাকাউন্ট নম্বর",
        "ifsc code" to "আইএফএসসি কোড",
        "bank name" to "ব্যাংকের নাম",
        "pan number" to "প্যান নম্বর",
        "aadhaar number" to "আধার নম্বর",
        "doorstep visits" to "ডোরস্টেপ পরিদর্শন",
        "field agent cockpit" to "ফিল্ড এজেন্ট ককপিট",
        "platform overview" to "প্ল্যাটফর্ম ওভারভিউ",
        "audit trail" to "অডিট ট্রেইল",
        "add pledge" to "বন্ধক যোগ করুন",
        "disbursement request" to "বিতরণ অনুরোধ",
        "sign agreement" to "চুক্তিতে স্বাক্ষর করুন",
        "pay now" to "এখন দিন",
        "pay directly with upi app" to "সরাসরি ইউপিআই অ্যাপ দিয়ে পেমেন্ট করুন",
        "sign in to your account" to "আপনার অ্যাকাউন্টে সাইন ইন করুন",
        "fast-track with didit ai" to "ডিডিট এআই দিয়ে দ্রুত করুন",
        "30 sec kyc" to "30 সেকেন্ড কেওয়াইসি",
        "or manual verification" to "অথবা ম্যানুয়াল যাচাইকরণ",
        "complete kyc" to "কেওয়াইসি সম্পূর্ণ করুন",
        "kyc complete!" to "কেওয়াইসি সম্পন্ন!",
        "your profile is now verified" to "আপনার প্রোফাইল এখন যাচাইকৃত",
        "borrower dashboard" to "ঋণগ্রহীতা ড্যাশবোর্ড",
        "lender dashboard" to "ঋণদাতা ড্যাশবোর্ড",
        "tab_lent" to "ধার দেওয়া (Lent)",
        "tab_borrowed" to "ধার নেওয়া (Borrowed)",
        "total" to "মোট",
        "enter upi transaction id" to "ইউপিআই লেনদেন আইডি লিখুন",
        "save signature" to "স্বাক্ষর সংরক্ষণ করুন",
        "loan dashboard" to "ঋণ ড্যাশবোর্ড"
    )

    private val glossary_te = mapOf<String, String>(
        "created on" to "సృష్టించిన తేదీ",
        "repaid on" to "చెల్లించిన తేదీ",
        "disbursed on" to "పంపిణీ చేసిన తేదీ",
        "in progress" to "పురోగతిలో ఉంది",
        "step" to "దశ",
        "restructure loan" to "రుణాన్ని పునర్నిర్మించండి",
        "settlement" to "పరిష్కారం",
        "mediation" to "మధ్యవర్తిత్వం",
        "schedule mediation" to "మధ్యవర్తిత్వాన్ని షెడ్యూల్ చేయండి",
        "anti-harassment sos" to "యాంటీ-వేధింపుల SOS",
        "dispute tribunal" to "వివాద ట్రిబ్యునల్",
        "select option" to "ఎంపికను ఎంచుకోండి",
        "upi transaction reference" to "UPI లావాదేవీ రిఫరెన్స్",
        "quick select" to "శీఘ్ర ఎంపిక",
        "i am a" to "నేను ఒక",
        "join the verified lending platform" to "ధృవీకరించబడిన లెండింగ్ ప్లాట్‌ఫారమ్‌లో చేరండి",
        "verified loan utilization" to "ధృవీకరించబడిన రుణ వినియోగం",
        "certified agent cockpit & doorstep visits" to "సర్టిఫైడ్ ఏజెంట్ కాక్‌పిట్ & డోర్‌స్టెప్ సందర్శనలు",
        "verify identity (digilocker kyc)" to "గుర్తింపును ధృవీకరించండి (డిజిలాకర్ KYC)",
        "calculate loan emi & savings" to "రుణ EMI & పొదుపులను లెక్కించండి",
        "explore community loan wall" to "కమ్యూనిటీ లోన్ వాల్ చూడండి",
        "submit tranche request" to "విడత అభ్యర్థనను సమర్పించండి",
        "rule engine result" to "రూల్ ఇంజిన్ ఫలితం",
        "weight (grams)" to "బరువు (గ్రాములు)",
        "estimated value" to "అంచనా విలువ",
        "asset type" to "ఆస్తి రకం",
        "asset description" to "ఆస్తి వివరణ",
        "asset collateral details" to "ఆస్తి తాకట్టు వివరాలు",
        "payee upi id" to "చెల్లింపుదారు UPI ఐడి",
        "payee name" to "చెల్లింపుదారు పేరు",
        "request tranche" to "విడతను అభ్యర్థించండి",
        "incorrect password" to "తప్పుడు పాస్‌వర్డ్",
        "unlock" to "అన్‌లాక్ చేయి",
        "enter password to unlock" to "అన్‌లాక్ చేయడానికి పాస్‌వర్డ్ నమోదు చేయండి",
        "unlock document vault" to "డాక్యుమెంట్ వాల్ట్ అన్‌లాక్ చేయండి",
        "close" to "మూసివేయి",
        "are you sure you want to sign out?" to "మీరు ఖచ్చితంగా సైన్ అవుట్ చేయాలనుకుంటున్నారా?",
        "confirm logout" to "లాగ్ అవుట్ నిర్ధారించండి",
        "home" to "హోమ్",
        "loans" to "రుణాలు",
        "loan" to "రుణం",
        "alerts" to "హెచ్చరికలు",
        "profile" to "ప్రొఫైల్",
        "notifications" to "నోటిఫికేషన్లు",
        "marketplace" to "మార్కెట్ ప్లేస్",
        "explore marketplace" to "మార్కెట్‌ప్లేస్‌ను అన్వేషించండి",
        "community wall" to "కమ్యూనిటీ వాల్",
        "community loan wall" to "కమ్యూనిటీ లోన్ వాల్",
        "portfolio overview" to "పోర్ట్‌ఫోలియో అవలోకనం",
        "active portfolio value" to "యాక్టివ్ పోర్ట్‌ఫోలియో విలువ",
        "real-time capital balance" to "రియల్ టైమ్ క్యాపిటల్ బ్యాలెన్స్",
        "recent activity" to "ఇటీవలి కార్యాచరణ",
        "quick actions" to "శీఘ్ర చర్యలు",
        "apply for loan" to "రుణం కోసం దరఖాస్తు చేయండి",
        "create new loan" to "కొత్త రుణం సృష్టించండి",
        "manage all loans" to "అన్ని రుణాలను నిర్వహించండి",
        "my loans" to "నా రుణాలు",
        "active loans" to "యాక్టివ్ రుణాలు",
        "total lent" to "మొత్తం అప్పు ఇచ్చినది",
        "total borrowed" to "మొత్తం అప్పు తీసుకున్నది",
        "lent out" to "అప్పు ఇచ్చినది",
        "borrowed" to "అప్పు తీసుకున్నది",
        "total outstanding" to "మొత్తం బాకీ",
        "total disbursed" to "మొత్తం పంపిణీ చేయబడింది",
        "total paid" to "మొత్తం చెల్లించినది",
        "sanctioned amount" to "మంజూరు చేసిన మొత్తం",
        "outstanding balance" to "బాకీ బ్యాలెన్స్",
        "monthly emi" to "నెలవారీ EMI",
        "interest rate" to "వడ్డీ రేటు",
        "tenure" to "వ్యవధి",
        "tenure (months)" to "వ్యవధి (నెలలు)",
        "loan amount" to "రుణ మొత్తం",
        "purpose" to "ప్రయోజనం",
        "repay now" to "ఇప్పుడే చెల్లించండి",
        "make repayment" to "తిరిగి చెల్లించండి",
        "repayment schedule" to "చెల్లింపు షెడ్యూల్",
        "repayment history" to "చెల్లింపు చరిత్ర",
        "member" to "సభ్యుడు",
        "user" to "వినియోగదారు",
        "borrower" to "రుణగ్రహీత",
        "lender" to "రుణదాత",
        "field agent" to "ఫీల్డ్ ఏజెంట్",
        "master admin" to "మాస్టర్ అడ్మిన్",
        "app owner" to "యాప్ యజమాని",
        "guarantor" to "హామీదారు",
        "in-app role switcher" to "ఇన్-యాప్ రోల్ స్విచ్చర్",
        "verified" to "ధృవీకరించబడింది",
        "pending" to "పెండింగ్‌లో ఉంది",
        "approved" to "ఆమోదించబడింది",
        "rejected" to "తిరస్కరించబడింది",
        "completed" to "పూర్తయింది",
        "sanctioned" to "మంజూరైనది",
        "disbursed" to "పంపిణీ చేయబడింది",
        "repaid" to "తిరిగి చెల్లించబడింది",
        "overdue" to "గడువు ముగిసింది",
        "active" to "యాక్టివ్",
        "closed" to "ముగిసింది",
        "locked" to "లాక్ 🔒",
        "unlocked" to "అన్‌లాక్ 🔓",
        "on duty" to "డ్యూటీలో ఉన్నారు",
        "off duty" to "ఆఫ్ డ్యూటీ",
        "settings" to "సెట్టింగ్‌లు",
        "app language" to "యాప్ భాష",
        "change language" to "భాషను మార్చండి",
        "select app language" to "యాప్ భాషను ఎంచుకోండి",
        "appearance" to "రూపం",
        "sign out" to "సైన్ అవుట్",
        "logout" to "లాగ్ అవుట్",
        "trust score" to "ట్రస్ట్ స్కోర్",
        "digilocker" to "డిజిలాకర్",
        "vault" to "వాల్ట్",
        "kyc verification" to "KYC ధృవీకరణ",
        "bank details" to "బ్యాంక్ వివరాలు",
        "bank accounts" to "బ్యాంక్ ఖాతాలు",
        "security & biometrics" to "భద్రత మరియు బయోమెట్రిక్స్",
        "help & support" to "సహాయం మరియు మద్దతు",
        "loan calculator" to "రుణ కాలిక్యులేటర్",
        "save" to "భద్రపరచు",
        "cancel" to "రద్దు చేయి",
        "clear" to "క్లియర్ చేయి",
        "submit" to "సమర్పించు",
        "confirm" to "ధృవీకరించండి",
        "continue" to "కొనసాగించండి",
        "next" to "తదుపరి",
        "back" to "వెనుకకు",
        "search" to "వెతకండి",
        "edit" to "సవరించు",
        "delete" to "తొలగించు",
        "upload" to "అప్‌లోడ్ చేయండి",
        "download" to "డౌన్‌లోడ్ చేయండి",
        "sign in" to "సైన్ ఇన్ చేయండి",
        "create account" to "ఖాతాను సృష్టించండి",
        "register" to "నమోదు చేసుకోండి",
        "phone number" to "ఫోన్ నంబర్",
        "email address" to "ఇమెయిల్ చిరునామా",
        "full name" to "పూర్తి పేరు",
        "password" to "పాస్‌వర్డ్",
        "welcome to loanzo" to "లోన్జోకు స్వాగతం",
        "welcome back" to "తిరిగి స్వాగతం",
        "thank you" to "ధన్యవాదాలు",
        "yes" to "అవును",
        "no" to "కాదు",
        "ok" to "సరే",
        "okay" to "సరే",
        "all offers" to "అన్ని ఆఫర్లు",
        "lenders" to "రుణదాతలు",
        "borrowers" to "రుణగ్రహీతలు",
        "my posts" to "నా పోస్ట్‌లు",
        "post" to "పోస్ట్",
        "create post" to "పోస్ట్ సృష్టించండి",
        "bid" to "బిడ్ వేయండి",
        "bids" to "బిడ్లు",
        "submit bid" to "బిడ్ సమర్పించండి",
        "vouch" to "ధృవీకరించండి",
        "vouches" to "ధృవీకరణలు",
        "vouch for post" to "ఈ పోస్ట్‌కు హామీ ఇవ్వండి",
        "all" to "అన్నీ",
        "filter" to "ఫిల్టర్",
        "sort" to "క్రమబద్ధీకరించు",
        "chat" to "చాట్",
        "report" to "నివేదిక",
        "simulator" to "సిమ్యులేటర్",
        "guide" to "గైడ్",
        "interactive guide" to "ఇంటరాక్టివ్ గైడ్",
        "loan details" to "రుణ వివరాలు",
        "principal" to "అసలు",
        "interest" to "వడ్డీ",
        "penalty" to "జరిమానా",
        "due date" to "గడువు తేదీ",
        "status" to "స్థితి",
        "amount" to "మొత్తం",
        "date" to "తేదీ",
        "time" to "సమయం",
        "upi id" to "UPI ఐడి",
        "account number" to "ఖాతా సంఖ్య",
        "ifsc code" to "IFSC కోడ్",
        "bank name" to "బ్యాంక్ పేరు",
        "pan number" to "పాన్ నంబర్",
        "aadhaar number" to "ఆధార్ సంఖ్య",
        "doorstep visits" to "డోర్‌స్టెప్ సందర్శనలు",
        "field agent cockpit" to "ఫీల్డ్ ఏజెంట్ కాక్‌పిట్",
        "platform overview" to "ప్లాట్‌ఫారమ్ అవలోకనం",
        "audit trail" to "ఆడిట్ ట్రయిల్",
        "add pledge" to "తాకట్టు జోడించండి",
        "disbursement request" to "పంపిణీ అభ్యర్థన",
        "sign agreement" to "ఒప్పందంపై సంతకం చేయండి",
        "pay now" to "ఇప్పుడే చెల్లించండి",
        "pay directly with upi app" to "నేరుగా UPI యాప్‌తో చెల్లించండి",
        "sign in to your account" to "మీ ఖాతాలోకి సైన్ ఇన్ చేయండి",
        "fast-track with didit ai" to "డిడిట్ AI తో వేగవంతం చేయండి",
        "30 sec kyc" to "30 సెకన్ల KYC",
        "or manual verification" to "లేదా మాన్యువల్ ధృవీకరణ",
        "complete kyc" to "KYC పూర్తి చేయండి",
        "kyc complete!" to "KYC పూర్తయింది!",
        "your profile is now verified" to "మీ ప్రొఫైల్ ఇప్పుడు ధృవీకరించబడింది",
        "borrower dashboard" to "రుణగ్రహీత డాష్‌బోర్డ్",
        "lender dashboard" to "రుణదాత డాష్‌బోర్డ్",
        "tab_lent" to "అప్పు ఇచ్చినది (Lent)",
        "tab_borrowed" to "అప్పు తీసుకున్నది (Borrowed)",
        "total" to "మొత్తం",
        "enter upi transaction id" to "UPI లావాదేవీ ID నమోదు చేయండి",
        "save signature" to "సంతకాన్ని భద్రపరచండి",
        "loan dashboard" to "రుణ డాష్‌బోర్డ్"
    )

    private val glossary_ta = mapOf<String, String>(
        "created on" to "உருவாக்கப்பட்ட தேதி",
        "repaid on" to "செலுத்தப்பட்ட தேதி",
        "disbursed on" to "வழங்கப்பட்ட தேதி",
        "in progress" to "செயலில் உள்ளது",
        "step" to "படி",
        "restructure loan" to "கடனை மறுசீரமைக்கவும்",
        "settlement" to "ஒப்பந்தம்",
        "mediation" to "மத்தியஸ்தம்",
        "schedule mediation" to "மத்தியஸ்தத்தை திட்டமிடுங்கள்",
        "anti-harassment sos" to "துன்புறுத்தல் எதிர்ப்பு எஸ்ஓஎஸ்",
        "dispute tribunal" to "சர்ச்சை தீர்ப்பாயம்",
        "select option" to "விருப்பத்தைத் தேர்ந்தெடுக்கவும்",
        "upi transaction reference" to "யுபிஐ பரிவர்த்தனை குறிப்பு",
        "quick select" to "விரைவு தேர்வு",
        "i am a" to "நான் ஒரு",
        "join the verified lending platform" to "சரிபார்க்கப்பட்ட கடன் தளத்தில் இணையுங்கள்",
        "verified loan utilization" to "சரிபார்க்கப்பட்ட கடன் பயன்பாடு",
        "certified agent cockpit & doorstep visits" to "சான்றளிக்கப்பட்ட முகவர் காக்பிட் & வீட்டு வாசலில் சந்திப்புகள்",
        "verify identity (digilocker kyc)" to "அடையாளத்தை சரிபார்க்கவும் (டிஜிலாக்கர் கேஒய்சி)",
        "calculate loan emi & savings" to "கடன் இஎம்ஐ & சேமிப்பை கணக்கிடுங்கள்",
        "explore community loan wall" to "சமூக கடன் சுவரை ஆராயுங்கள்",
        "submit tranche request" to "தவணை கோரிக்கையைச் சமர்ப்பிக்கவும்",
        "rule engine result" to "விதி இயந்திர முடிவு",
        "weight (grams)" to "எடை (கிராம்கள்)",
        "estimated value" to "மதிப்பிடப்பட்ட மதிப்பு",
        "asset type" to "சொத்து வகை",
        "asset description" to "சொத்து விளக்கம்",
        "asset collateral details" to "சொத்து அடமான விவரங்கள்",
        "payee upi id" to "பெறுபவரின் யுபிஐ ஐடி",
        "payee name" to "பணம் பெறுபவர் பெயர்",
        "request tranche" to "தவணை கோரிக்கை",
        "incorrect password" to "தவறான கடவுச்சொல்",
        "unlock" to "திற",
        "enter password to unlock" to "திறக்க கடவுச்சொல்லை உள்ளிடவும்",
        "unlock document vault" to "ஆவண பெட்டகத்தைத் திறக்கவும்",
        "close" to "மூடு",
        "are you sure you want to sign out?" to "நிச்சயமாக வெளியேற விரும்புகிறீர்களா?",
        "confirm logout" to "வெளியேறுவதை உறுதிப்படுத்தவும்",
        "home" to "முகப்பு",
        "loans" to "கடன்கள்",
        "loan" to "கடன்",
        "alerts" to "எச்சரிக்கைகள்",
        "profile" to "சுயவிவரம்",
        "notifications" to "அறிவிப்புகள்",
        "marketplace" to "சந்தை",
        "explore marketplace" to "சந்தையை ஆராயுங்கள்",
        "community wall" to "சமூக சுவர்",
        "community loan wall" to "சமூக கடன் சுவர்",
        "portfolio overview" to "போர்ட்ஃபோலியோ கண்ணோட்டம்",
        "active portfolio value" to "செயலில் உள்ள போர்ட்ஃபோலியோ மதிப்பு",
        "real-time capital balance" to "நிகழ்நேர மூலதன இருப்பு",
        "recent activity" to "சமீபத்திய செயல்பாடு",
        "quick actions" to "விரைவான செயல்கள்",
        "apply for loan" to "கடனுக்கு விண்ணப்பிக்கவும்",
        "create new loan" to "புதிய கடனை உருவாக்கவும்",
        "manage all loans" to "அனைத்து கடன்களையும் நிர்வகிக்கவும்",
        "my loans" to "எனது கடன்கள்",
        "active loans" to "செயலில் உள்ள கடன்கள்",
        "total lent" to "மொத்த கடன் வழங்கப்பட்டது",
        "total borrowed" to "மொத்த கடன் பெறப்பட்டது",
        "lent out" to "கடன் கொடுத்தது",
        "borrowed" to "கடன் வாங்கியது",
        "total outstanding" to "மொத்த நிலுவை",
        "total disbursed" to "மொத்தம் வழங்கப்பட்டது",
        "total paid" to "மொத்தம் செலுத்தப்பட்டது",
        "sanctioned amount" to "ஒப்புதலளிக்கப்பட்ட தொகை",
        "outstanding balance" to "நிலுவைத் தொகை",
        "monthly emi" to "மாதாந்திர இஎம்ஐ",
        "interest rate" to "வட்டி விகிதம்",
        "tenure" to "கால அளவு",
        "tenure (months)" to "கால அளவு (மாதங்கள்)",
        "loan amount" to "கடன் தொகை",
        "purpose" to "நோக்கம்",
        "repay now" to "இப்போது திருப்பிச் செலுத்துங்கள்",
        "make repayment" to "திருப்பிச் செலுத்துங்கள்",
        "repayment schedule" to "திருப்பிச் செலுத்தும் அட்டவணை",
        "repayment history" to "திருப்பிச் செலுத்திய வரலாறு",
        "member" to "உறுப்பினர்",
        "user" to "பயனர்",
        "borrower" to "கடன் வாங்குபவர்",
        "lender" to "கடன் கொடுப்பவர்",
        "field agent" to "கள முகவர்",
        "master admin" to "முதன்மை நிர்வாகி",
        "app owner" to "பயன்பாட்டு உரிமையாளர்",
        "guarantor" to "உத்தரவாதமளிப்பவர்",
        "in-app role switcher" to "பயன்பாட்டு பாத்திர மாற்றி",
        "verified" to "சரிபார்க்கப்பட்டது",
        "pending" to "நிலுவையில் உள்ளது",
        "approved" to "அங்கீகரிக்கப்பட்டது",
        "rejected" to "நிராகரிக்கப்பட்டது",
        "completed" to "முடிந்தது",
        "sanctioned" to "ஒப்புதல் அளிக்கப்பட்டது",
        "disbursed" to "வழங்கப்பட்டது",
        "repaid" to "திருப்பிச் செலுத்தப்பட்டது",
        "overdue" to "தாமதமானது",
        "active" to "செயலில்",
        "closed" to "மூடப்பட்டது",
        "locked" to "பூட்டப்பட்டது 🔒",
        "unlocked" to "திறக்கப்பட்டது 🔓",
        "on duty" to "பணியில் உள்ளார்",
        "off duty" to "பணியில் இல்லை",
        "settings" to "அமைப்புகள்",
        "app language" to "பயன்பாட்டு மொழி",
        "change language" to "மொழியை மாற்றவும்",
        "select app language" to "பயன்பாட்டு மொழியைத் தேர்ந்தெடுக்கவும்",
        "appearance" to "தோற்றம்",
        "sign out" to "வெளியேறு",
        "logout" to "வெளியேறு",
        "trust score" to "நம்பகத்தன்மை மதிப்பெண்",
        "digilocker" to "டிஜிலாக்கர்",
        "vault" to "பெட்டகம்",
        "kyc verification" to "கேஒய்சி சரிபார்ப்பு",
        "bank details" to "வங்கி விவரங்கள்",
        "bank accounts" to "வங்கி கணக்குகள்",
        "security & biometrics" to "பாதுகாப்பு மற்றும் பயோமெட்ரிக்ஸ்",
        "help & support" to "உதவி & ஆதரவு",
        "loan calculator" to "கடன் கால்குலேட்டர்",
        "save" to "சேமிக்க",
        "cancel" to "ரத்துசெய்",
        "clear" to "அழி",
        "submit" to "சமர்ப்பிக்கவும்",
        "confirm" to "உறுதிப்படுத்துங்கள்",
        "continue" to "தொடரவும்",
        "next" to "அடுத்து",
        "back" to "பின்செல்",
        "search" to "தேடு",
        "edit" to "திருத்து",
        "delete" to "நீக்கு",
        "upload" to "பதிவேற்றவும்",
        "download" to "பதிவிறக்கவும்",
        "sign in" to "உள்நுழையவும்",
        "create account" to "கணக்கை உருவாக்கவும்",
        "register" to "பதிவு செய்யவும்",
        "phone number" to "தொலைபேசி எண்",
        "email address" to "மின்னஞ்சல் முகவரி",
        "full name" to "முழு பெயர்",
        "password" to "கடவுச்சொல்",
        "welcome to loanzo" to "லோன்சோவிற்கு வரவேற்கிறோம்",
        "welcome back" to "மீண்டும் வருக",
        "thank you" to "நன்றி",
        "yes" to "ஆம்",
        "no" to "இல்லை",
        "ok" to "சரி",
        "okay" to "சரி",
        "all offers" to "அனைத்து சலுகைகளும்",
        "lenders" to "கடன் வழங்குபவர்கள்",
        "borrowers" to "கடன் வாங்குபவர்கள்",
        "my posts" to "எனது பதிவுகள்",
        "post" to "பதிவு",
        "create post" to "பதிவை உருவாக்கவும்",
        "bid" to "ஏலம் எடுங்கள்",
        "bids" to "ஏலங்கள்",
        "submit bid" to "ஏலத்தை சமர்ப்பிக்கவும்",
        "vouch" to "உறுதியளிக்கவும்",
        "vouches" to "உறுதிமொழிகள்",
        "vouch for post" to "இந்த பதிவுக்கு உறுதியளிக்கவும்",
        "all" to "அனைத்தும்",
        "filter" to "வடிகட்டு",
        "sort" to "வரிசைப்படுத்து",
        "chat" to "அரட்டை",
        "report" to "அறிக்கை",
        "simulator" to "சிமுலேட்டர்",
        "guide" to "வழிகாட்டி",
        "interactive guide" to "ஊடாடும் வழிகாட்டி",
        "loan details" to "கடன் விவரங்கள்",
        "principal" to "அசல்",
        "interest" to "வட்டி",
        "penalty" to "அபராதம்",
        "due date" to "செலுத்த வேண்டிய தேதி",
        "status" to "நிலை",
        "amount" to "தொகை",
        "date" to "தேதி",
        "time" to "நேரம்",
        "upi id" to "யுபிஐ ஐடி",
        "account number" to "கணக்கு எண்",
        "ifsc code" to "ஐஎஃப்எஸ்சி குறியீடு",
        "bank name" to "வங்கி பெயர்",
        "pan number" to "பான் எண்",
        "aadhaar number" to "ஆதார் எண்",
        "doorstep visits" to "வீட்டு வாசலில் சந்திப்பு",
        "field agent cockpit" to "கள முகவர் காக்பிட்",
        "platform overview" to "தள கண்ணோட்டம்",
        "audit trail" to "தணிக்கை பாதை",
        "add pledge" to "அடமானம் சேர்க்கவும்",
        "disbursement request" to "வழங்கல் கோரிக்கை",
        "sign agreement" to "ஒப்பந்தத்தில் கையெழுத்திடுங்கள்",
        "pay now" to "இப்போது செலுத்துங்கள்",
        "pay directly with upi app" to "நேரடியாக யுபிஐ ஆப் மூலம் செலுத்துங்கள்",
        "sign in to your account" to "உங்கள் கணக்கில் உள்நுழையவும்",
        "fast-track with didit ai" to "டிடிட் AI மூலம் விரைவுபடுத்துங்கள்",
        "30 sec kyc" to "30 வினாடி கேஒய்சி",
        "or manual verification" to "அல்லது கைமுறை சரிபார்ப்பு",
        "complete kyc" to "கேஒய்சி முடிக்கவும்",
        "kyc complete!" to "கேஒய்சி முடிந்தது!",
        "your profile is now verified" to "உங்கள் சுயவிவரம் இப்போது சரிபார்க்கப்பட்டது",
        "borrower dashboard" to "கடன் வாங்குபவர் டாஷ்போர்டு",
        "lender dashboard" to "கடன் வழங்குபவர் டாஷ்போர்டு",
        "tab_lent" to "வழங்கப்பட்டது (Lent)",
        "tab_borrowed" to "பெறப்பட்டது (Borrowed)",
        "total" to "மொத்தம்",
        "enter upi transaction id" to "யுபிஐ பரிவர்த்தனை ஐடியை உள்ளிடவும்",
        "save signature" to "கையொப்பத்தைச் சேமிக்கவும்",
        "loan dashboard" to "கடன் டாஷ்போர்டு"
    )

    private val glossary_kn = mapOf<String, String>(
        "created on" to "ರಚಿಸಿದ ದಿನಾಂಕ",
        "repaid on" to "ಮರುಪಾವತಿಸಿದ ದಿನಾಂಕ",
        "disbursed on" to "ವಿತರಿಸಿದ ದಿನಾಂಕ",
        "in progress" to "ಪ್ರಗತಿಯಲ್ಲಿದೆ",
        "step" to "ಹಂತ",
        "restructure loan" to "ಸಾಲವನ್ನು ಪುನರ್ರಚಿಸಿ",
        "settlement" to "ಇತ್ಯರ್ಥ",
        "mediation" to "ಮಧ್ಯಸ್ಥಿಕೆ",
        "schedule mediation" to "ಮಧ್ಯಸ್ಥಿಕೆಯನ್ನು ನಿಗದಿಪಡಿಸಿ",
        "anti-harassment sos" to "ಕಿರುಕುಳ ವಿರೋಧಿ SOS",
        "dispute tribunal" to "ವಿವಾದ ನ್ಯಾಯಮಂಡಳಿ",
        "select option" to "ಆಯ್ಕೆಯನ್ನು ಆರಿಸಿ",
        "upi transaction reference" to "ಯುಪಿಐ ವಹಿವಾಟು ಉಲ್ಲೇಖ",
        "quick select" to "ತ್ವರಿತ ಆಯ್ಕೆ",
        "i am a" to "ನಾನು ಒಬ್ಬ",
        "join the verified lending platform" to "ಪರಿಶೀಲಿಸಿದ ಸಾಲ ವೇದಿಕೆಗೆ ಸೇರಿ",
        "verified loan utilization" to "ಪರಿಶೀಲಿಸಿದ ಸಾಲ ಬಳಕೆ",
        "certified agent cockpit & doorstep visits" to "ಪ್ರಮಾಣೀಕೃತ ಏಜೆಂಟ್ ಕಾಕ್‌ಪಿಟ್ ಮತ್ತು ಮನೆ ಬಾಗಿಲಿನ ಭೇಟಿಗಳು",
        "verify identity (digilocker kyc)" to "ಗುರುತನ್ನು ಪರಿಶೀಲಿಸಿ (ಡಿಜಿಲಾಕರ್ KYC)",
        "calculate loan emi & savings" to "ಸಾಲ EMI ಮತ್ತು ಉಳಿತಾಯ ಲೆಕ್ಕಾಚಾರ ಮಾಡಿ",
        "explore community loan wall" to "ಸಮುದಾಯ ಸಾಲ ವಾಲ್ ನೋಡಿ",
        "submit tranche request" to "ಕಂತು ವಿನಂತಿಯನ್ನು ಸಲ್ಲಿಸಿ",
        "rule engine result" to "ರೂಲ್ ಇಂಜಿನ್ ಫಲಿತಾಂಶ",
        "weight (grams)" to "ತೂಕ (ಗ್ರಾಂ)",
        "estimated value" to "ಅಂದಾಜು ಮೌಲ್ಯ",
        "asset type" to "ಆಸ್ತಿ ಪ್ರಕಾರ",
        "asset description" to "ಆಸ್ತಿ ವಿವರಣೆ",
        "asset collateral details" to "ಆಸ್ತಿ ಅಡಮಾನ ವಿವರಗಳು",
        "payee upi id" to "ಸ್ವೀಕರಿಸುವವರ ಯುಪಿಐ ಐಡಿ",
        "payee name" to "ಸ್ವೀಕರಿಸುವವರ ಹೆಸರು",
        "request tranche" to "ಕಂತು ವಿನಂತಿ",
        "incorrect password" to "ತಪ್ಪು ಪಾಸ್‌ವರ್ಡ್",
        "unlock" to "ಅನ್‌ಲಾಕ್ ಮಾಡಿ",
        "enter password to unlock" to "ಅನ್‌ಲಾಕ್ ಮಾಡಲು ಪಾಸ್‌ವರ್ಡ್ ನಮೂದಿಸಿ",
        "unlock document vault" to "ದಾಖಲೆ ವಾಲ್ಟ್ ಅನ್‌ಲಾಕ್ ಮಾಡಿ",
        "close" to "ಮುಚ್ಚಿ",
        "are you sure you want to sign out?" to "ನೀವು ಖಚಿತವಾಗಿ ಸೈನ್ ಔಟ್ ಮಾಡಲು ಬಯಸುವಿರಾ?",
        "confirm logout" to "ಲಾಗ್ ಔಟ್ ದೃಢೀಕರಿಸಿ",
        "home" to "ಮುಖಪುಟ",
        "loans" to "ಸಾಲಗಳು",
        "loan" to "ಸಾಲ",
        "alerts" to "ಎಚ್ಚರಿಕೆಗಳು",
        "profile" to "ಪ್ರೊಫೈಲ್",
        "notifications" to "ಅಧಿಸೂಚನೆಗಳು",
        "marketplace" to "ಮಾರುಕಟ್ಟೆ",
        "explore marketplace" to "ಮಾರುಕಟ್ಟೆಯನ್ನು ಅನ್ವೇಷಿಸಿ",
        "community wall" to "ಸಮುದಾಯ ವಾಲ್",
        "community loan wall" to "ಸಮುದಾಯ ಸಾಲ ವಾಲ್",
        "portfolio overview" to "ಪೋರ್ಟ್ಫೋಲಿಯೋ ಅವಲೋಕನ",
        "active portfolio value" to "ಸಕ್ರಿಯ ಪೋರ್ಟ್ಫೋಲಿಯೋ ಮೌಲ್ಯ",
        "real-time capital balance" to "ನೈಜ-ಸಮಯದ ಬಂಡವಾಳ ಬಾಕಿ",
        "recent activity" to "ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ",
        "quick actions" to "ತ್ವರಿತ ಕ್ರಿಯೆಗಳು",
        "apply for loan" to "ಸಾಲಕ್ಕಾಗಿ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ",
        "create new loan" to "ಹೊಸ ಸಾಲವನ್ನು ರಚಿಸಿ",
        "manage all loans" to "ಎಲ್ಲಾ ಸಾಲಗಳನ್ನು ನಿರ್ವಹಿಸಿ",
        "my loans" to "ನನ್ನ ಸಾಲಗಳು",
        "active loans" to "ಸಕ್ರಿಯ ಸಾಲಗಳು",
        "total lent" to "ಒಟ್ಟು ನೀಡಿದ ಸಾಲ",
        "total borrowed" to "ಒಟ್ಟು ಪಡೆದ ಸಾಲ",
        "lent out" to "ನೀಡಿದ ಸಾಲ",
        "borrowed" to "ಪಡೆದ ಸಾಲ",
        "total outstanding" to "ಒಟ್ಟು ಬಾಕಿ",
        "total disbursed" to "ಒಟ್ಟು ವಿತರಿಸಲಾಗಿದೆ",
        "total paid" to "ಒಟ್ಟು ಪಾವತಿಸಲಾಗಿದೆ",
        "sanctioned amount" to "ಮಂಜೂರಾದ ಮೊತ್ತ",
        "outstanding balance" to "ಬಾಕಿ ಮೊತ್ತ",
        "monthly emi" to "ಮಾಸಿಕ EMI",
        "interest rate" to "ಬಡ್ಡಿ ದರ",
        "tenure" to "ಅವಧಿ",
        "tenure (months)" to "ಅವಧಿ (ತಿಂಗಳುಗಳು)",
        "loan amount" to "ಸಾಲದ ಮೊತ್ತ",
        "purpose" to "ಉದ್ದೇಶ",
        "repay now" to "ಈಗಲೇ ಮರುಪಾವತಿಸಿ",
        "make repayment" to "ಮರುಪಾವತಿ ಮಾಡಿ",
        "repayment schedule" to "ಮರುಪಾವತಿ ವೇಳಾಪಟ್ಟಿ",
        "repayment history" to "ಮರುಪಾವತಿ ಇತಿಹಾಸ",
        "member" to "ಸದಸ್ಯ",
        "user" to "ಬಳಕೆದಾರ",
        "borrower" to "ಸಾಲಗಾರ",
        "lender" to "ಸಾಲದಾತ",
        "field agent" to "ಫೀಲ್ಡ್ ಏಜೆಂಟ್",
        "master admin" to "ಮಾಸ್ಟರ್ ಅಡ್ಮಿನ್",
        "app owner" to "ಆ್ಯಪ್ ಮಾಲೀಕ",
        "guarantor" to "ಖಾತರಿದಾರ",
        "in-app role switcher" to "ಇನ್-ಆ್ಯಪ್ ಪಾತ್ರ ಬದಲಾವಣೆ",
        "verified" to "ಪರಿಶೀಲಿಸಲಾಗಿದೆ",
        "pending" to "ಬಾಕಿ ಉಳಿದಿದೆ",
        "approved" to "ಅನುಮೋದಿಸಲಾಗಿದೆ",
        "rejected" to "ತಿರಸ್ಕರಿಸಲಾಗಿದೆ",
        "completed" to "ಪೂರ್ಣಗೊಂಡಿದೆ",
        "sanctioned" to "ಮಂಜೂರಾಗಿದೆ",
        "disbursed" to "ವಿತರಿಸಲಾಗಿದೆ",
        "repaid" to "ಮರುಪಾವತಿಸಲಾಗಿದೆ",
        "overdue" to "ಗಡುವು ಮೀರಿದೆ",
        "active" to "ಸಕ್ರಿಯ",
        "closed" to "ಮುಕ್ತಾಯಗೊಂಡಿದೆ",
        "locked" to "ಲಾಕ್ ಆಗಿದೆ 🔒",
        "unlocked" to "ಅನ್‌ಲಾಕ್ ಆಗಿದೆ 🔓",
        "on duty" to "ಕರ್ತವ್ಯದಲ್ಲಿದ್ದಾರೆ",
        "off duty" to "ಕರ್ತವ್ಯದಿಂದ ಹೊರಗೆ",
        "settings" to "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
        "app language" to "ಆ್ಯಪ್ ಭಾಷೆ",
        "change language" to "ಭಾಷೆಯನ್ನು ಬದಲಾಯಿಸಿ",
        "select app language" to "ಆ್ಯಪ್ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
        "appearance" to "ಗೋಚರತೆ",
        "sign out" to "ಸೈನ್ ಔಟ್",
        "logout" to "ಲಾಗ್ ಔಟ್",
        "trust score" to "ವಿಶ್ವಾಸಾರ್ಹತೆ ಸ್ಕೋರ್",
        "digilocker" to "ಡಿಜಿಲಾಕರ್",
        "vault" to "ವಾಲ್ಟ್",
        "kyc verification" to "KYC ಪರಿಶೀಲನೆ",
        "bank details" to "ಬ್ಯಾಂಕ್ ವಿವರಗಳು",
        "bank accounts" to "ಬ್ಯಾಂಕ್ ಖಾತೆಗಳು",
        "security & biometrics" to "ಭದ್ರತೆ ಮತ್ತು ಬಯೋಮೆಟ್ರಿಕ್ಸ್",
        "help & support" to "ಸಹಾಯ ಮತ್ತು ಬೆಂಬಲ",
        "loan calculator" to "ಸಾಲ ಕ್ಯಾಲ್ಕುಲೇಟರ್",
        "save" to "ಉಳಿಸಿ",
        "cancel" to "ರದ್ದುಮಾಡಿ",
        "clear" to "ತೆರವುಗೊಳಿಸಿ",
        "submit" to "ಸಲ್ಲಿಸಿ",
        "confirm" to "ದೃಢೀಕರಿಸಿ",
        "continue" to "ಮುಂದುವರಿಸಿ",
        "next" to "ಮುಂದೆ",
        "back" to "ಹಿಂದೆ",
        "search" to "ಹುಡುಕಿ",
        "edit" to "ತಿದ್ದಿ",
        "delete" to "ಅಳಿಸಿ",
        "upload" to "ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
        "download" to "ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ",
        "sign in" to "ಸೈನ್ ಇನ್ ಮಾಡಿ",
        "create account" to "ಖಾತೆ ರಚಿಸಿ",
        "register" to "ನೋಂದಾಯಿಸಿ",
        "phone number" to "ಫೋನ್ ಸಂಖ್ಯೆ",
        "email address" to "ಇಮೇಲ್ ವಿಳಾಸ",
        "full name" to "ಪೂರ್ಣ ಹೆಸರು",
        "password" to "ಪಾಸ್‌ವರ್ಡ್",
        "welcome to loanzo" to "ಲೋನ್ಜೋಗೆ ಸುಸ್ವಾಗತ",
        "welcome back" to "ಮರಳಿ ಸ್ವಾಗತ",
        "thank you" to "ಧನ್ಯವಾದಗಳು",
        "yes" to "ಹೌದು",
        "no" to "ಇಲ್ಲ",
        "ok" to "ಸರಿ",
        "okay" to "ಸರಿ",
        "all offers" to "ಎಲ್ಲಾ ಆಫರ್‌ಗಳು",
        "lenders" to "ಸಾಲದಾತರು",
        "borrowers" to "ಸಾಲಗಾರರು",
        "my posts" to "ನನ್ನ ಪೋಸ್ಟ್‌ಗಳು",
        "post" to "ಪೋಸ್ಟ್",
        "create post" to "ಪೋಸ್ಟ್ ರಚಿಸಿ",
        "bid" to "ಬಿಡ್ ಮಾಡಿ",
        "bids" to "ಬಿಡ್‌ಗಳು",
        "submit bid" to "ಬಿಡ್ ಸಲ್ಲಿಸಿ",
        "vouch" to "ಖಾತರಿ ನೀಡಿ",
        "vouches" to "ಖಾತರಿಗಳು",
        "vouch for post" to "ಈ ಪೋಸ್ಟ್‌ಗೆ ಖಾತರಿ ನೀಡಿ",
        "all" to "ಎಲ್ಲಾ",
        "filter" to "ಫಿಲ್ಟರ್",
        "sort" to "ವಿಂಗಡಿಸಿ",
        "chat" to "ಚಾಟ್",
        "report" to "ವರದಿ",
        "simulator" to "ಸಿಮ್ಯುಲೇಟರ್",
        "guide" to "ಮಾರ್ಗದರ್ಶಿ",
        "interactive guide" to "ಸಂವಾದಾತ್ಮಕ ಮಾರ್ಗದರ್ಶಿ",
        "loan details" to "ಸಾಲದ ವಿವರಗಳು",
        "principal" to "ಅಸಲು",
        "interest" to "ಬಡ್ಡಿ",
        "penalty" to "ದಂಡ",
        "due date" to "ಗಡುವು ದಿನಾಂಕ",
        "status" to "ಸ್ಥಿತಿ",
        "amount" to "ಮೊತ್ತ",
        "date" to "ದಿನಾಂಕ",
        "time" to "ಸಮಯ",
        "upi id" to "ಯುಪಿಐ ಐಡಿ",
        "account number" to "ಖಾತೆ ಸಂಖ್ಯೆ",
        "ifsc code" to "ಐಎಫ್‌ಎಸ್‌ಸಿ ಕೋಡ್",
        "bank name" to "ಬ್ಯಾಂಕ್ ಹೆಸರು",
        "pan number" to "ಪ್ಯಾನ್ ಸಂಖ್ಯೆ",
        "aadhaar number" to "ಆಧಾರ್ ಸಂಖ್ಯೆ",
        "doorstep visits" to "ಮನೆ ಬಾಗಿಲಿನ ಭೇಟಿಗಳು",
        "field agent cockpit" to "ಫೀಲ್ಡ್ ಏಜೆಂಟ್ ಕಾಕ್‌ಪಿಟ್",
        "platform overview" to "ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ಅವಲೋಕನ",
        "audit trail" to "ಆಡಿಟ್ ಟ್ರಯಲ್",
        "add pledge" to "ಅಡಮಾನ ಸೇರಿಸಿ",
        "disbursement request" to "ವಿತರಣಾ ವಿನಂತಿ",
        "sign agreement" to "ಒಪ್ಪಂದಕ್ಕೆ ಸಹಿ ಮಾಡಿ",
        "pay now" to "ಈಗ ಪಾವತಿಸಿ",
        "pay directly with upi app" to "ನೇರವಾಗಿ ಯುಪಿಐ ಆ್ಯಪ್ ಮೂಲಕ ಪಾವತಿಸಿ",
        "sign in to your account" to "ನಿಮ್ಮ ಖಾತೆಗೆ ಸೈನ್ ಇನ್ ಮಾಡಿ",
        "fast-track with didit ai" to "ಡಿಡಿಟ್ AI ನೊಂದಿಗೆ ವೇಗಗೊಳಿಸಿ",
        "30 sec kyc" to "30 ಸೆಕೆಂಡುಗಳ KYC",
        "or manual verification" to "ಅಥವಾ ಹಸ್ತಚಾಲಿತ ಪರಿಶೀಲನೆ",
        "complete kyc" to "KYC ಪೂರ್ಣಗೊಳಿಸಿ",
        "kyc complete!" to "KYC ಪೂರ್ಣಗೊಂಡಿದೆ!",
        "your profile is now verified" to "ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಈಗ ಪರಿಶೀಲಿಸಲಾಗಿದೆ",
        "borrower dashboard" to "ಸಾಲಗಾರ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
        "lender dashboard" to "ಸಾಲದಾತ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
        "tab_lent" to "ನೀಡಿದ ಸಾಲ (Lent)",
        "tab_borrowed" to "ಪಡೆದ ಸಾಲ (Borrowed)",
        "total" to "ಒಟ್ಟು",
        "enter upi transaction id" to "ಯುಪಿಐ ವಹಿವಾಟು ಐಡಿ ನಮೂದಿಸಿ",
        "save signature" to "ಸಹಿಯನ್ನು ಉಳಿಸಿ",
        "loan dashboard" to "ಸಾಲ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್"
    )

    private val glossary_pa = mapOf<String, String>(
        "created on" to "ਬਣਾਉਣ ਦੀ ਮਿਤੀ",
        "repaid on" to "ਭੁਗਤਾਨ ਦੀ ਮਿਤੀ",
        "disbursed on" to "ਵੰਡਣ ਦੀ ਮਿਤੀ",
        "in progress" to "ਜਾਰੀ ਹੈ",
        "step" to "ਕਦਮ",
        "restructure loan" to "ਕਰਜ਼ੇ ਦਾ ਪੁਨਰਗਠਨ ਕਰੋ",
        "settlement" to "ਨਿਪਟਾਰਾ",
        "mediation" to "ਵਿਚੋਲਗੀ",
        "schedule mediation" to "ਮੱਧਸਥਤਾ ਨਿਰਧਾਰਤ ਕਰੋ",
        "anti-harassment sos" to "ਪਰੇਸ਼ਾਨੀ ਵਿਰੋਧੀ ਐਸਓਐਸ",
        "dispute tribunal" to "ਵਿਵਾਦ ਟ੍ਰਿਬਿਊਨਲ",
        "select option" to "ਵਿਕਲਪ ਚੁਣੋ",
        "upi transaction reference" to "ਯੂਪੀਆਈ ਲੈਣ-ਦੇਣ ਹਵਾਲਾ",
        "quick select" to "ਤੁਰੰਤ ਚੋਣ",
        "i am a" to "ਮੈਂ ਇੱਕ ਹਾਂ",
        "join the verified lending platform" to "ਪ੍ਰਮਾਣਿਤ ਉਧਾਰ ਪਲੇਟਫਾਰਮ ਨਾਲ ਜੁੜੋ",
        "verified loan utilization" to "ਪ੍ਰਮਾਣਿਤ ਕਰਜ਼ਾ ਵਰਤੋਂ",
        "certified agent cockpit & doorstep visits" to "ਪ੍ਰਮਾਣਿਤ ਏਜੰਟ ਕਾਕਪਿਟ ਅਤੇ ਘਰ-ਘਰ ਫੇਰੀਆਂ",
        "verify identity (digilocker kyc)" to "ਪਛਾਣ ਪ੍ਰਮਾਣਿਤ ਕਰੋ (ਡਿਜੀਲਾਕਰ ਕੇਵਾਈਸੀ)",
        "calculate loan emi & savings" to "ਕਰਜ਼ਾ EMI ਅਤੇ ਬੱਚਤ ਦੀ ਗਣਨਾ ਕਰੋ",
        "explore community loan wall" to "ਕਮਿਊਨਿਟੀ ਲੋਨ ਵਾਲ ਵੇਖੋ",
        "submit tranche request" to "ਕਿਸ਼ਤ ਬੇਨਤੀ ਜਮ੍ਹਾਂ ਕਰੋ",
        "rule engine result" to "ਨਿਯਮ ਇੰਜਨ ਨਤੀਜਾ",
        "weight (grams)" to "ਭਾਰ (ਗ੍ਰਾਮ)",
        "estimated value" to "ਅੰਦਾਜ਼ਨ ਮੁੱਲ",
        "asset type" to "ਜਾਇਦਾਦ ਦੀ ਕਿਸਮ",
        "asset description" to "ਜਾਇਦਾਦ ਦਾ ਵੇਰਵਾ",
        "asset collateral details" to "ਜਾਇਦਾਦ ਗਹਿਣੇ ਵੇਰਵੇ",
        "payee upi id" to "ਪ੍ਰਾਪਤਕਰਤਾ ਯੂਪੀਆਈ ਆਈਡੀ",
        "payee name" to "ਭੁਗਤਾਨ ਕਰਤਾ ਦਾ ਨਾਂ",
        "request tranche" to "ਕਿਸ਼ਤ ਦੀ ਬੇਨਤੀ ਕਰੋ",
        "incorrect password" to "ਗਲਤ ਪਾਸਵਰਡ",
        "unlock" to "ਅਨਲੌਕ ਕਰੋ",
        "enter password to unlock" to "ਅਨਲੌਕ ਕਰਨ ਲਈ ਪਾਸਵਰਡ ਦਰਜ ਕਰੋ",
        "unlock document vault" to "ਦਸਤਾਵੇਜ਼ ਵਾਲਟ ਅਨਲੌਕ ਕਰੋ",
        "close" to "ਬੰਦ ਕਰੋ",
        "are you sure you want to sign out?" to "ਕੀ ਤੁਸੀਂ ਯਕੀਨਨ ਸਾਈਨ ਆਊਟ ਕਰਨਾ ਚਾਹੁੰਦੇ ਹੋ?",
        "confirm logout" to "ਲਾਗ ਆਊਟ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ",
        "home" to "ਹੋਮ",
        "loans" to "ਕਰਜ਼ੇ",
        "loan" to "ਕਰਜ਼ਾ",
        "alerts" to "ਚਿਤਾਵਨੀਆਂ",
        "profile" to "ਪ੍ਰੋਫਾਈਲ",
        "notifications" to "ਨੋਟੀਫਿਕੇਸ਼ਨ",
        "marketplace" to "ਮਾਰਕੀਟਪਲੇਸ",
        "explore marketplace" to "ਮਾਰਕੀਟਪਲੇਸ ਐਕਸਪਲੋਰ ਕਰੋ",
        "community wall" to "ਕਮਿਊਨਿਟੀ ਵਾਲ",
        "community loan wall" to "ਕਮਿਊਨਿਟੀ ਲੋਨ ਵਾਲ",
        "portfolio overview" to "ਪੋਰਟਫੋਲੀਓ ਸੰਖੇਪ",
        "active portfolio value" to "ਐਕਟਿਵ ਪੋਰਟਫੋਲੀਓ ਮੁੱਲ",
        "real-time capital balance" to "ਰੀਅਲ-ਟਾਈਮ ਪੂੰਜੀ ਬਕਾਇਆ",
        "recent activity" to "ਹਾਲੀਆ ਗਤੀਵਿਧੀ",
        "quick actions" to "ਤੁਰੰਤ ਕਾਰਵਾਈਆਂ",
        "apply for loan" to "ਕਰਜ਼ੇ ਲਈ ਅਰਜ਼ੀ ਦਿਓ",
        "create new loan" to "ਨਵਾਂ ਕਰਜ਼ਾ ਬਣਾਓ",
        "manage all loans" to "ਸਾਰੇ ਕਰਜ਼ਿਆਂ ਦਾ ਪ੍ਰਬੰਧਨ ਕਰੋ",
        "my loans" to "ਮੇਰੇ ਕਰਜ਼ੇ",
        "active loans" to "ਐਕਟਿਵ ਕਰਜ਼ੇ",
        "total lent" to "ਕੁੱਲ ਦਿੱਤਾ ਕਰਜ਼ਾ",
        "total borrowed" to "ਕੁੱਲ ਲਿਆ ਕਰਜ਼ਾ",
        "lent out" to "ਦਿੱਤਾ ਕਰਜ਼ਾ",
        "borrowed" to "ਲਿਆ ਕਰਜ਼ਾ",
        "total outstanding" to "ਕੁੱਲ ਬਕਾਇਆ",
        "total disbursed" to "ਕੁੱਲ ਵੰਡਿਆ",
        "total paid" to "ਕੁੱਲ ਭੁਗਤਾਨ",
        "sanctioned amount" to "ਮਨਜ਼ੂਰਸ਼ੁਦਾ ਰਕਮ",
        "outstanding balance" to "ਬਕਾਇਆ ਰਕਮ",
        "monthly emi" to "ਮਹੀਨਾਵਾਰ EMI",
        "interest rate" to "ਵਿਆਜ ਦਰ",
        "tenure" to "ਮਿਆਦ",
        "tenure (months)" to "ਮਿਆਦ (ਮਹੀਨੇ)",
        "loan amount" to "ਕਰਜ਼ੇ ਦੀ ਰਕਮ",
        "purpose" to "ਮਕਸਦ",
        "repay now" to "ਹੁਣੇ ਭੁਗਤਾਨ ਕਰੋ",
        "make repayment" to "ਭੁਗਤਾਨ ਕਰੋ",
        "repayment schedule" to "ਭੁਗਤਾਨ ਅਨੁਸੂਚੀ",
        "repayment history" to "ਭੁਗਤਾਨ ਇਤਿਹਾਸ",
        "member" to "ਮੈਂਬਰ",
        "user" to "ਉਪਭੋਗਤਾ",
        "borrower" to "ਉਧਾਰ ਲੈਣ ਵਾਲਾ",
        "lender" to "ਕਰਜ਼ਾ ਦੇਣ ਵਾਲਾ",
        "field agent" to "ਫੀਲਡ ਏਜੰਟ",
        "master admin" to "ਮਾਸਟਰ ਐਡਮਿਨ",
        "app owner" to "ਐਪ ਮਾਲਕ",
        "guarantor" to "ਜ਼ਾਮਿਨ",
        "in-app role switcher" to "ਇਨ-ਐਪ ਭੂਮਿਕਾ ਸਵਿਚਰ",
        "verified" to "ਪ੍ਰਮਾਣਿਤ",
        "pending" to "ਬਕਾਇਆ",
        "approved" to "ਮਨਜ਼ੂਰ",
        "rejected" to "ਰੱਦ",
        "completed" to "ਮੁਕੰਮਲ",
        "sanctioned" to "ਮਨਜ਼ੂਰ",
        "disbursed" to "ਵੰਡਿਆ ਗਿਆ",
        "repaid" to "ਭੁਗਤਾਨ ਕੀਤਾ",
        "overdue" to "ਮਿਆਦ ਪੁੱਗੀ",
        "active" to "ਸਰਗਰਮ",
        "closed" to "ਬੰਦ",
        "locked" to "ਲਾਕ 🔒",
        "unlocked" to "ਅਨਲੌਕ 🔓",
        "on duty" to "ਡਿਊਟੀ 'ਤੇ",
        "off duty" to "ਆਫ ਡਿਊਟੀ",
        "settings" to "ਸੈਟਿੰਗਾਂ",
        "app language" to "ਐਪ ਭਾਸ਼ਾ",
        "change language" to "ਭਾਸ਼ਾ ਬਦਲੋ",
        "select app language" to "ਐਪ ਭਾਸ਼ਾ ਚੁਣੋ",
        "appearance" to "ਦਿੱਖ",
        "sign out" to "ਸਾਈਨ ਆਊਟ",
        "logout" to "ਲਾਗ ਆਊਟ",
        "trust score" to "ਵਿਸ਼ਵਾਸ ਸਕੋਰ",
        "digilocker" to "ਡਿਜੀਲਾਕਰ",
        "vault" to "ਵਾਲਟ",
        "kyc verification" to "ਕੇਵਾਈਸੀ ਪ੍ਰਮਾਣੀਕਰਨ",
        "bank details" to "ਬੈਂਕ ਵੇਰਵੇ",
        "bank accounts" to "ਬੈਂਕ ਖਾਤੇ",
        "security & biometrics" to "ਸੁਰੱਖਿਆ ਅਤੇ ਬਾਇਓਮੈਟ੍ਰਿਕਸ",
        "help & support" to "ਮਦਦ ਅਤੇ ਸਹਾਇਤਾ",
        "loan calculator" to "ਕਰਜ਼ਾ ਕੈਲਕੁਲੇਟਰ",
        "save" to "ਸੰਭਾਲੋ",
        "cancel" to "ਰੱਦ ਕਰੋ",
        "clear" to "ਸਾਫ਼ ਕਰੋ",
        "submit" to "ਜਮ੍ਹਾਂ ਕਰੋ",
        "confirm" to "ਪੁਸ਼ਟੀ ਕਰੋ",
        "continue" to "ਜਾਰੀ ਰੱਖੋ",
        "next" to "ਅਗਲਾ",
        "back" to "ਪਿੱਛੇ",
        "search" to "ਖੋਜੋ",
        "edit" to "ਸੰਪਾਦਿਤ ਕਰੋ",
        "delete" to "ਮਿਟਾਓ",
        "upload" to "ਅੱਪਲੋਡ ਕਰੋ",
        "download" to "ਡਾਊਨਲੋਡ ਕਰੋ",
        "sign in" to "ਸਾਈਨ ਇਨ ਕਰੋ",
        "create account" to "ਖਾਤਾ ਬਣਾਓ",
        "register" to "ਰਜਿਸਟਰ ਕਰੋ",
        "phone number" to "ਫ਼ੋਨ ਨੰਬਰ",
        "email address" to "ਈਮੇਲ ਪਤਾ",
        "full name" to "ਪੂਰਾ ਨਾਂ",
        "password" to "ਪਾਸਵਰਡ",
        "welcome to loanzo" to "ਲੋਨਜ਼ੋ ਵਿੱਚ ਤੁਹਾਡਾ ਸੁਆਗਤ ਹੈ",
        "welcome back" to "ਜੀ ਆਇਆਂ ਨੂੰ",
        "thank you" to "ਧੰਨਵਾਦ",
        "yes" to "ਹਾਂ",
        "no" to "ਨਹੀਂ",
        "ok" to "ਠੀਕ ਹੈ",
        "okay" to "ਠੀਕ ਹੈ",
        "all offers" to "ਸਾਰੀਆਂ ਪੇਸ਼ਕਸ਼ਾਂ",
        "lenders" to "ਕਰਜ਼ਾ ਦੇਣ ਵਾਲੇ",
        "borrowers" to "ਉਧਾਰ ਲੈਣ ਵਾਲੇ",
        "my posts" to "ਮੇਰੀਆਂ ਪੋਸਟਾਂ",
        "post" to "ਪੋਸਟ",
        "create post" to "ਪੋਸਟ ਬਣਾਓ",
        "bid" to "ਬੋਲੀ ਲਗਾਓ",
        "bids" to "ਬੋਲੀਆਂ",
        "submit bid" to "ਬੋਲੀ ਜਮ੍ਹਾਂ ਕਰੋ",
        "vouch" to "ਜ਼ਾਮਿਨੀ ਭਰੋ",
        "vouches" to "ਜ਼ਾਮਿਨੀਆਂ",
        "vouch for post" to "ਇਸ ਪੋਸਟ ਲਈ ਜ਼ਾਮਿਨੀ ਭਰੋ",
        "all" to "ਸਾਰੇ",
        "filter" to "ਫਿਲਟਰ",
        "sort" to "ਤਰਤੀਬ ਦਿਓ",
        "chat" to "ਚੈਟ",
        "report" to "ਰਿਪੋਰਟ",
        "simulator" to "ਸਿਮੂਲੇਟਰ",
        "guide" to "ਗਾਈਡ",
        "interactive guide" to "ਇੰਟਰਐਕਟਿਵ ਗਾਈਡ",
        "loan details" to "ਕਰਜ਼ੇ ਦੇ ਵੇਰਵੇ",
        "principal" to "ਮੂਲਧਨ",
        "interest" to "ਵਿਆਜ",
        "penalty" to "ਜੁਰਮਾਨਾ",
        "due date" to "ਆਖਰੀ ਮਿਤੀ",
        "status" to "ਸਥਿਤੀ",
        "amount" to "ਰਕਮ",
        "date" to "ਮਿਤੀ",
        "time" to "ਸਮਾਂ",
        "upi id" to "ਯੂਪੀਆਈ ਆਈਡੀ",
        "account number" to "ਖਾਤਾ ਨੰਬਰ",
        "ifsc code" to "ਆਈਐਫਐਸਸੀ ਕੋਡ",
        "bank name" to "ਬੈਂਕ ਦਾ ਨਾਂ",
        "pan number" to "ਪੈਨ ਨੰਬਰ",
        "aadhaar number" to "ਆਧਾਰ ਨੰਬਰ",
        "doorstep visits" to "ਘਰ ਘਰ ਫੇਰੀਆਂ",
        "field agent cockpit" to "ਫੀਲਡ ਏਜੰਟ ਕਾਕਪਿਟ",
        "platform overview" to "ਪਲੇਟਫਾਰਮ ਸੰਖੇਪ",
        "audit trail" to "ਆਡਿਟ ਟ੍ਰੇਲ",
        "add pledge" to "ਗਹਿਣੇ ਜੋੜੋ",
        "disbursement request" to "ਵੰਡ ਬੇਨਤੀ",
        "sign agreement" to "ਸਮਝੌਤੇ 'ਤੇ ਦਸਤਖਤ ਕਰੋ",
        "pay now" to "ਹੁਣੇ ਭੁਗਤਾਨ ਕਰੋ",
        "pay directly with upi app" to "ਸਿੱਧੇ ਯੂਪੀਆਈ ਐਪ ਨਾਲ ਭੁਗਤਾਨ ਕਰੋ",
        "sign in to your account" to "ਆਪਣੇ ਖਾਤੇ ਵਿੱਚ ਸਾਈਨ ਇਨ ਕਰੋ",
        "fast-track with didit ai" to "ਡਿਡਿਟ AI ਨਾਲ ਤੇਜ਼ ਕਰੋ",
        "30 sec kyc" to "30 ਸਕਿੰਟ ਕੇਵਾਈਸੀ",
        "or manual verification" to "ਜਾਂ ਮੈਨੂਅਲ ਪ੍ਰਮਾਣੀਕਰਨ",
        "complete kyc" to "ਕੇਵਾਈਸੀ ਪੂਰਾ ਕਰੋ",
        "kyc complete!" to "ਕੇਵਾਈਸੀ ਪੂਰਾ!",
        "your profile is now verified" to "ਤੁਹਾਡੀ ਪ੍ਰੋਫਾਈਲ ਹੁਣ ਪ੍ਰਮਾਣਿਤ ਹੈ",
        "borrower dashboard" to "ਉਧਾਰ ਲੈਣ ਵਾਲਾ ਡੈਸ਼ਬੋਰਡ",
        "lender dashboard" to "ਕਰਜ਼ਾ ਦੇਣ ਵਾਲਾ ਡੈਸ਼ਬੋਰਡ",
        "tab_lent" to "ਦਿੱਤਾ ਕਰਜ਼ਾ (Lent)",
        "tab_borrowed" to "ਲਿਆ ਕਰਜ਼ਾ (Borrowed)",
        "total" to "ਕੁੱਲ",
        "enter upi transaction id" to "ਯੂਪੀਆਈ ਲੈਣ-ਦੇਣ ਆਈਡੀ ਦਰਜ ਕਰੋ",
        "save signature" to "ਦਸਤਖਤ ਸੰਭਾਲੋ",
        "loan dashboard" to "ਕਰਜ਼ਾ ਡੈਸ਼ਬੋਰਡ"
    )

    fun getTranslation(text: String, targetLang: String): String? {
        val lang = targetLang.lowercase().trim()
        if (lang == "en" || text.isBlank()) return text
        val cleaned = text.trim()
        val lower = cleaned.lowercase()

        val map = when (lang) {
            "hi" -> glossary_hi
            "mr" -> glossary_mr
            "gu" -> glossary_gu
            "bn" -> glossary_bn
            "te" -> glossary_te
            "ta" -> glossary_ta
            "kn" -> glossary_kn
            "pa" -> glossary_pa
            else -> glossary_hi // fallback to Hindi for other Indian locales
        }

        // 1. Direct exact match
        map[lower]?.let { return it }

        // 2. Trailing punctuation handling (e.g. "Due Date:", "Amount?")
        if (lower.endsWith(":") || lower.endsWith("?") || lower.endsWith("!")) {
            val punct = lower.takeLast(1)
            val base = lower.dropLast(1).trim()
            map[base]?.let { return "$it$punct" }
        }

        // 3. Parentheses handling (e.g. "(Optional)", "(3)")
        if (lower.startsWith("(") && lower.endsWith(")")) {
            val inner = lower.substring(1, lower.length - 1).trim()
            map[inner]?.let { return "($it)" }
        }

        // 4. Currency or numeric preservation
        if (cleaned.startsWith("₹") || cleaned.startsWith("$") || cleaned.all { it.isDigit() || it == ',' || it == '.' || it == '/' || it == '-' || it == ' ' }) {
            return cleaned
        }

        // 5. Common prefix matching
        val prefixes = listOf("status:", "amount:", "due date:", "tenure:", "interest rate:", "loan id:", "ref:")
        for (pref in prefixes) {
            if (lower.startsWith(pref)) {
                val rest = cleaned.substring(pref.length).trim()
                val translatedPref = map[pref.dropLast(1)] ?: pref.dropLast(1)
                return "$translatedPref: $rest"
            }
        }

        return null
    }
}
