package com.loanzo.app.util

import android.content.Context
import android.content.Intent
import android.graphics.Canvas
import android.graphics.Paint
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import android.net.Uri
import androidx.core.content.FileProvider
import com.loanzo.app.data.entity.LoanEntity
import com.loanzo.app.data.entity.RepaymentEntity
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.*

/**
 * Generates PDF reports for loan summaries and interest certificates.
 * Uses Android's built-in PdfDocument API — no external dependencies.
 */
object ReportGenerator {

    private val dateFormat = SimpleDateFormat("dd MMM yyyy", Locale.getDefault())

    fun generateLoanSummaryPdf(
        context: Context,
        loan: LoanEntity,
        repayments: List<RepaymentEntity>
    ): Uri? {
        val document = PdfDocument()
        val pageInfo = PdfDocument.PageInfo.Builder(595, 842, 1).create() // A4
        val page = document.startPage(pageInfo)
        val canvas = page.canvas

        val titlePaint = Paint().apply { textSize = 22f; typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD); isAntiAlias = true }
        val headerPaint = Paint().apply { textSize = 14f; typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD); isAntiAlias = true }
        val bodyPaint = Paint().apply { textSize = 12f; isAntiAlias = true }
        val lightPaint = Paint().apply { textSize = 10f; color = android.graphics.Color.GRAY; isAntiAlias = true }

        var y = 50f
        val margin = 40f

        // Title
        canvas.drawText("LOANZO — Loan Summary Report", margin, y, titlePaint)
        y += 10f
        canvas.drawLine(margin, y, 555f, y, lightPaint)
        y += 30f

        // Loan details
        canvas.drawText("Loan Details", margin, y, headerPaint); y += 22f
        val details = listOf(
            "Loan ID" to loan.loanId,
            "Purpose" to loan.purpose,
            "Type" to loan.loanType,
            "Sanctioned" to "₹${String.format(java.util.Locale.getDefault(), "%,.2f", loan.sanctionedAmount)}",
            "Outstanding" to "₹${String.format(java.util.Locale.getDefault(), "%,.2f", loan.outstandingAmount)}",
            "Interest" to "${loan.interestRate}% (${loan.interestModel})",
            "Tenure" to "${loan.tenureMonths} months",
            "Status" to loan.status,
            "Created" to dateFormat.format(Date(loan.createdAt))
        )
        details.forEach { (label, value) ->
            canvas.drawText("$label:", margin, y, bodyPaint)
            canvas.drawText(value, margin + 150f, y, bodyPaint)
            y += 18f
        }

        y += 20f
        canvas.drawText("Repayment History", margin, y, headerPaint); y += 22f

        if (repayments.isEmpty()) {
            canvas.drawText("No repayments recorded yet.", margin, y, bodyPaint)
        } else {
            // Table header
            canvas.drawText("Amount", margin, y, headerPaint)
            canvas.drawText("Status", margin + 120f, y, headerPaint)
            canvas.drawText("Due Date", margin + 220f, y, headerPaint)
            canvas.drawText("Paid Date", margin + 340f, y, headerPaint)
            y += 18f

            repayments.take(25).forEach { rep ->
                if (y > 780f) return@forEach // prevent overflow
                canvas.drawText("₹${String.format(java.util.Locale.getDefault(), "%,.2f", rep.amount)}", margin, y, bodyPaint)
                canvas.drawText(rep.status, margin + 120f, y, bodyPaint)
                canvas.drawText(dateFormat.format(Date(rep.dueDate)), margin + 220f, y, bodyPaint)
                canvas.drawText(if (rep.paidDate != null) dateFormat.format(Date(rep.paidDate)) else "—", margin + 340f, y, bodyPaint)
                y += 16f
            }
        }

        // Footer
        canvas.drawText("Generated by Loanzo on ${dateFormat.format(Date())}", margin, 820f, lightPaint)

        document.finishPage(page)

        return savePdfAndGetUri(context, document, "loan_summary_${loan.loanId}.pdf")
    }

    fun generateInterestCertificatePdf(
        context: Context,
        loan: LoanEntity,
        repayments: List<RepaymentEntity>,
        financialYear: String
    ): Uri? {
        val document = PdfDocument()
        val pageInfo = PdfDocument.PageInfo.Builder(595, 842, 1).create()
        val page = document.startPage(pageInfo)
        val canvas = page.canvas

        val titlePaint = Paint().apply { textSize = 22f; typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD); isAntiAlias = true }
        val headerPaint = Paint().apply { textSize = 14f; typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD); isAntiAlias = true }
        val bodyPaint = Paint().apply { textSize = 12f; isAntiAlias = true }
        val lightPaint = Paint().apply { textSize = 10f; color = android.graphics.Color.GRAY; isAntiAlias = true }

        var y = 50f
        val margin = 40f

        canvas.drawText("INTEREST CERTIFICATE", margin, y, titlePaint); y += 10f
        canvas.drawLine(margin, y, 555f, y, lightPaint); y += 30f

        canvas.drawText("Financial Year: $financialYear", margin, y, headerPaint); y += 30f

        val totalInterest = repayments.filter { it.status == "PAID" }.sumOf { it.interestComponent }
        val totalPrincipal = repayments.filter { it.status == "PAID" }.sumOf { it.principalComponent }

        val items = listOf(
            "Loan ID" to loan.loanId,
            "Loan Type" to loan.loanType,
            "Total Principal Repaid" to "₹${String.format(java.util.Locale.getDefault(), "%,.2f", totalPrincipal)}",
            "Total Interest Paid" to "₹${String.format(java.util.Locale.getDefault(), "%,.2f", totalInterest)}",
            "Interest Rate" to "${loan.interestRate}%",
            "Interest Model" to loan.interestModel
        )
        items.forEach { (label, value) ->
            canvas.drawText("$label:", margin, y, bodyPaint)
            canvas.drawText(value, margin + 200f, y, bodyPaint)
            y += 20f
        }

        y += 30f
        canvas.drawText("This certificate is issued for income tax purposes.", margin, y, bodyPaint)
        y += 40f
        canvas.drawText("Generated by Loanzo on ${dateFormat.format(Date())}", margin, y, lightPaint)

        document.finishPage(page)
        return savePdfAndGetUri(context, document, "interest_cert_${loan.loanId}_$financialYear.pdf")
    }

    private fun savePdfAndGetUri(context: Context, document: PdfDocument, filename: String): Uri? {
        return try {
            val file = File(context.cacheDir, filename)
            FileOutputStream(file).use { document.writeTo(it) }
            document.close()
            FileProvider.getUriForFile(context, "${context.packageName}.fileprovider", file)
        } catch (e: Exception) {
            e.printStackTrace()
            document.close()
            null
        }
    }

    fun shareUri(context: Context, uri: Uri) {
        val intent = Intent(Intent.ACTION_VIEW).apply {
            setDataAndType(uri, "application/pdf")
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }
        context.startActivity(Intent.createChooser(intent, "Open Report"))
    }
}
